<?php

return [
    'system_roles' => [
        'admin' => 'Admin',
        'hrd' => 'HRD',
        'manager' => 'Manager',
        'applicant' => 'Applicant',
        'candidate' => 'Candidate',
        'employee' => 'Employee',
        'probation' => 'Probation',
    ],

    'permissions' => [
        'settings.view' => ['label' => 'View Settings', 'group' => 'Settings'],
        'settings.manage' => ['label' => 'Manage Settings', 'group' => 'Settings'],
        'users_roles.manage' => ['label' => 'Manage Users and Roles', 'group' => 'Settings'],

        'applicants.view' => ['label' => 'View Applicants', 'group' => 'Recruitment'],
        'applicants.manage' => ['label' => 'Manage Applicants', 'group' => 'Recruitment'],
        'applicants.review' => ['label' => 'Tandai Applicant Sudah Direview', 'group' => 'Recruitment'],
        'applicants.bulk_action' => ['label' => 'Aksi Massal Applicant', 'group' => 'Recruitment'],
        'candidates.view' => ['label' => 'View Candidates', 'group' => 'Recruitment'],
        'candidates.manage' => ['label' => 'Manage Candidates', 'group' => 'Recruitment'],
        'candidates.create' => ['label' => 'Tambah Candidate', 'group' => 'Recruitment'],
        'candidates.update' => ['label' => 'Edit Candidate', 'group' => 'Recruitment'],
        'candidates.delete' => ['label' => 'Hapus Candidate', 'group' => 'Recruitment'],
        'candidates.accept' => ['label' => 'Terima Candidate', 'group' => 'Recruitment'],
        'candidates.reject' => ['label' => 'Tolak Candidate', 'group' => 'Recruitment'],
        'candidates.block' => ['label' => 'Blokir Candidate', 'group' => 'Recruitment'],
        'candidates.restore' => ['label' => 'Pulihkan Candidate', 'group' => 'Recruitment'],
        'candidates.bulk_status' => ['label' => 'Ubah Status Massal Candidate', 'group' => 'Recruitment'],
        'candidates.assessment_update' => ['label' => 'Input Skor Assessment Candidate', 'group' => 'Recruitment'],
        'candidates.export' => ['label' => 'Export Data Candidate', 'group' => 'Recruitment'],
        'tests.manage' => ['label' => 'Manage Recruitment Tests', 'group' => 'Recruitment'],

        'contracts.templates.manage' => ['label' => 'Manage Contract Templates', 'group' => 'Contracts'],
        'contracts.send' => ['label' => 'Send Contracts', 'group' => 'Contracts'],
        'contracts.review' => ['label' => 'Review Contracts', 'group' => 'Contracts'],

        'employees.view' => ['label' => 'View Employees', 'group' => 'Employees'],
        'employees.manage' => ['label' => 'Manage Employees', 'group' => 'Employees'],
        'employees.create' => ['label' => 'Tambah Karyawan', 'group' => 'Employees'],
        'employees.update' => ['label' => 'Edit Data Karyawan', 'group' => 'Employees'],
        'employees.delete' => ['label' => 'Hapus Karyawan', 'group' => 'Employees'],
        'profile_changes.review' => ['label' => 'Review Profile Changes', 'group' => 'Employees'],

        'departments.view' => ['label' => 'Lihat Departemen', 'group' => 'Employees'],
        'departments.manage' => ['label' => 'Manage Departments', 'group' => 'Employees'],
        'positions.view' => ['label' => 'Lihat Posisi', 'group' => 'Employees'],
        'positions.manage' => ['label' => 'Manage Positions', 'group' => 'Employees'],
        'outlets.view' => ['label' => 'Lihat Outlet', 'group' => 'Employees'],
        'outlets.manage' => ['label' => 'Manage Outlets', 'group' => 'Employees'],
        'attendance.reports.view' => ['label' => 'View Attendance Reports', 'group' => 'Employees'],
        'training.manage' => ['label' => 'Manage Training', 'group' => 'Training'],
        'appraisals.view' => ['label' => 'Lihat Laporan Appraisal', 'group' => 'Appraisal'],
        'appraisals.manage' => ['label' => 'Manage Appraisals', 'group' => 'Appraisal'],
        'appraisals.approve' => ['label' => 'Approve/Exclude Penilaian Appraisal', 'group' => 'Appraisal'],
        'appraisals.assign' => ['label' => 'Assign Evaluator Appraisal', 'group' => 'Appraisal'],
        'appraisals.print' => ['label' => 'Cetak/Export Laporan Appraisal', 'group' => 'Appraisal'],
        'tasks.manage' => ['label' => 'Manage Tasks & Projects', 'group' => 'Employees'],
        'tasks.view' => ['label' => 'Lihat Papan Tugas', 'group' => 'Employees'],
        'tasks.create' => ['label' => 'Tambah Tugas', 'group' => 'Employees'],
        'tasks.update' => ['label' => 'Edit Tugas', 'group' => 'Employees'],
        'tasks.delete' => ['label' => 'Hapus Tugas', 'group' => 'Employees'],
        'notifications.manage' => ['label' => 'Manage Notifications', 'group' => 'General'],

        'finance.view'          => ['label' => 'Lihat Finance Dashboard',    'group' => 'Finance'],
        'finance.import'        => ['label' => 'Import Data Payroll',         'group' => 'Finance'],
        'finance.import.review' => ['label' => 'Review & Konfirmasi Import',  'group' => 'Finance'],
        'finance.bpjs.view'     => ['label' => 'Lihat Data BPJS',            'group' => 'Finance'],
        'finance.bpjs.manage'   => ['label' => 'Kelola Status Bayar BPJS',   'group' => 'Finance'],
        'finance.export'        => ['label' => 'Export Laporan Finance',      'group' => 'Finance'],

        'master.company_groups.manage' => ['label' => 'Kelola Group Perusahaan',      'group' => 'Master Lanjutan'],
        'master.legal_entities.manage' => ['label' => 'Kelola Entitas Legal (PT/CV)', 'group' => 'Master Lanjutan'],
        'master.regions.manage'        => ['label' => 'Kelola Regional & UMR',        'group' => 'Master Lanjutan'],
        'finance.bpjs.rates.manage'    => ['label' => 'Kelola Tarif BPJS per Regional','group' => 'Finance'],
        'finance.bpjs.legal.manage'    => ['label' => 'Kelola Akun Legal BPJS',       'group' => 'Finance'],
        'master.positions.manage'      => ['label' => 'Kelola Master Posisi/Jabatan', 'group' => 'Master Lanjutan'],
    ],

    'legacy_role_permissions' => [
        'admin' => ['*'],
        'finance' => [
            'finance.view',
            'finance.import',
            'finance.import.review',
            'finance.bpjs.view',
            'finance.bpjs.manage',
            'finance.export',
            'finance.bpjs.rates.manage',
            'finance.bpjs.legal.manage',
        ],
        'hrd' => [
            'settings.view',
            'settings.manage',
            'users_roles.manage',
            'applicants.view',
            'applicants.manage',
            'applicants.review',
            'applicants.bulk_action',
            'candidates.view',
            'candidates.manage',
            'candidates.create',
            'candidates.update',
            'candidates.delete',
            'candidates.accept',
            'candidates.reject',
            'candidates.block',
            'candidates.restore',
            'candidates.bulk_status',
            'candidates.assessment_update',
            'candidates.export',
            'tests.manage',
            'contracts.templates.manage',
            'contracts.send',
            'contracts.review',
            'employees.view',
            'employees.manage',
            'employees.create',
            'employees.update',
            'employees.delete',
            'profile_changes.review',
            'departments.view',
            'departments.manage',
            'positions.view',
            'positions.manage',
            'outlets.view',
            'outlets.manage',
            'attendance.reports.view',
            'training.manage',
            'appraisals.view',
            'appraisals.manage',
            'appraisals.approve',
            'appraisals.assign',
            'appraisals.print',
            'tasks.manage',
            'tasks.view',
            'tasks.create',
            'tasks.update',
            'tasks.delete',
            'notifications.manage',
            'master.company_groups.manage',
            'master.legal_entities.manage',
            'master.regions.manage',
            'master.positions.manage',
        ],
        'manager' => [
            'settings.view',
            'applicants.view',
            'candidates.view',
            'employees.view',
            'appraisals.view',
            'appraisals.manage',
            'appraisals.approve',
            'appraisals.assign',
            'appraisals.print',
            'tasks.manage',
            'tasks.view',
            'tasks.create',
            'tasks.update',
            'tasks.delete',
            'notifications.manage',
        ],
        'employee' => [],
        'probation' => [],
        'candidate' => [],
        'applicant' => [],
    ],

    'route_permissions' => [
        'dashboard' => ['settings.view'],
        'hrd.dashboard' => ['settings.view'],

        'settings.index' => ['settings.view'],
        'settings.update' => ['settings.manage'],
        'settings.recruitment-retention.*' => ['settings.manage'],

        'hrd.users.*' => ['settings.manage', 'users_roles.manage'],
        'hrd.roles.*' => ['settings.manage', 'users_roles.manage'],
        'hrd.settings.user-roles.*' => ['settings.manage', 'users_roles.manage'],

        'employees.index' => ['employees.view'],
        'employees.show' => ['employees.view'],
        'employees.create' => ['employees.manage', 'employees.create'],
        'employees.store' => ['employees.manage', 'employees.create'],
        'employees.edit' => ['employees.manage', 'employees.update'],
        'employees.update' => ['employees.manage', 'employees.update'],
        'employees.destroy' => ['employees.manage', 'employees.delete'],
        'employees.*' => ['employees.manage'],

        'departments.index' => ['departments.manage', 'departments.view'],
        'departments.create' => ['departments.manage'],
        'departments.store' => ['departments.manage'],
        'departments.edit' => ['departments.manage'],
        'departments.update' => ['departments.manage'],
        'departments.destroy' => ['departments.manage'],
        'departments.*' => ['departments.manage'],

        'positions.index' => ['positions.manage', 'positions.view'],
        'positions.org-chart' => ['positions.manage', 'positions.view'],
        'positions.employees' => ['positions.manage', 'positions.view'],
        'positions.*' => ['positions.manage'],

        'tasks.index' => ['tasks.manage', 'tasks.view'],
        'tasks.store' => ['tasks.manage', 'tasks.create'],
        'tasks.update' => ['tasks.manage', 'tasks.update'],
        'tasks.destroy' => ['tasks.manage', 'tasks.delete'],
        'tasks.*' => ['tasks.manage'],
        'projects.*' => ['tasks.manage'],

        'outlets.index' => ['outlets.manage', 'outlets.view'],
        'outlets.create' => ['outlets.manage'],
        'outlets.store' => ['outlets.manage'],
        'outlets.edit' => ['outlets.manage'],
        'outlets.update' => ['outlets.manage'],
        'outlets.destroy' => ['outlets.manage'],
        'outlets.*' => ['outlets.manage'],
        'hrd.attendance.*' => ['attendance.reports.view'],
        'hrd.probation-verifications.*' => ['profile_changes.review'],

        'hrd.applicants.index' => ['applicants.view'],
        'hrd.applicants.show' => ['applicants.view'],
        'hrd.applicants.export-pdf' => ['applicants.view'],
        'hrd.applicants.reviewed' => ['applicants.manage', 'applicants.review'],
        'hrd.applicants.bulk-action' => ['applicants.manage', 'applicants.bulk_action'],
        'hrd.applicants.govern' => ['applicants.manage', 'applicants.bulk_action'],
        'hrd.passed-candidates.*' => ['candidates.view'],

        'candidates.index' => ['candidates.view'],
        'candidates.show' => ['candidates.view'],
        'candidates.profile' => ['candidates.view'],
        'candidates.export-pdf' => ['candidates.view', 'candidates.export'],
        'candidates.create' => ['candidates.manage', 'candidates.create'],
        'candidates.store' => ['candidates.manage', 'candidates.create'],
        'candidates.edit' => ['candidates.manage', 'candidates.update'],
        'candidates.update' => ['candidates.manage', 'candidates.update'],
        'candidates.destroy' => ['candidates.manage', 'candidates.delete'],
        'candidates.accept' => ['candidates.manage', 'candidates.accept'],
        'candidates.reject' => ['candidates.manage', 'candidates.reject'],
        'candidates.block' => ['candidates.manage', 'candidates.block'],
        'candidates.restore' => ['candidates.manage', 'candidates.restore'],
        'candidates.bulk-status' => ['candidates.manage', 'candidates.bulk_status'],
        'candidates.bulk-activate' => ['candidates.manage', 'candidates.bulk_status'],
        'candidates.assessment.update' => ['candidates.manage', 'candidates.assessment_update'],
        'candidates.tests.*' => ['tests.manage'],
        'candidates.bulk-activate-tests' => ['tests.manage'],

        'hrd.contract-templates.*' => ['contracts.templates.manage'],
        'hrd.contracts.index' => ['contracts.review'],
        'hrd.contracts.show' => ['contracts.review'],
        'hrd.contracts.download' => ['contracts.review'],
        'hrd.contracts.review' => ['contracts.review'],
        'hrd.contracts.send' => ['contracts.send'],
        'offering.*' => ['contracts.send'],

        'training-materials.*' => ['training.manage'],
        'hrd.forms.*' => ['tests.manage'],
        'hrd.import.iq.*' => ['tests.manage'],
        'hrd.import.disc.*' => ['tests.manage'],

        'appraisal-periods.*' => ['appraisals.manage'],
        'appraisal-indicators.*' => ['appraisals.manage'],
        'appraisals.index' => ['appraisals.manage', 'appraisals.view'],
        'appraisals.approve' => ['appraisals.manage', 'appraisals.approve'],
        'appraisals.assign' => ['appraisals.manage', 'appraisals.assign'],
        'appraisals.print' => ['appraisals.manage', 'appraisals.print'],

        'hr-notifications.*' => ['notifications.manage'],

        'master.company-groups.*'    => ['master.company_groups.manage'],
        'master.legal-entities.*'    => ['master.legal_entities.manage'],
        'master.regions.*'           => ['master.regions.manage'],
        'finance.bpjs-rates.*'       => ['finance.bpjs.rates.manage'],
        'finance.bpjs-legal.*'       => ['finance.bpjs.legal.manage'],

        'finance.*'                  => ['finance.view'],
        'finance.import.create'      => ['finance.import'],
        'finance.import.store'       => ['finance.import'],
        'finance.import.row.action'  => ['finance.import.review'],
        'finance.import.confirm-all' => ['finance.import.review'],
        'finance.bpjs.*'             => ['finance.bpjs.view'],
        'finance.bpjs.payment.*'     => ['finance.bpjs.manage'],
    ],
];
