<?php

return [
    'system_roles' => [
        'admin' => 'Admin',
        'hrd' => 'HRD',
        'manager' => 'Manager',
        'applicant' => 'Applicant',
        'candidate' => 'Candidate',
        'employee' => 'Employee',
        'probation' => 'Probation',
    ],

    'permissions' => [
        'settings.view' => ['label' => 'View Settings', 'group' => 'Settings'],
        'settings.manage' => ['label' => 'Manage Settings', 'group' => 'Settings'],
        'users_roles.manage' => ['label' => 'Manage Users and Roles', 'group' => 'Settings'],

        'applicants.view' => ['label' => 'View Applicants', 'group' => 'Recruitment'],
        'applicants.manage' => ['label' => 'Manage Applicants', 'group' => 'Recruitment'],
        'candidates.view' => ['label' => 'View Candidates', 'group' => 'Recruitment'],
        'candidates.manage' => ['label' => 'Manage Candidates', 'group' => 'Recruitment'],
        'tests.manage' => ['label' => 'Manage Recruitment Tests', 'group' => 'Recruitment'],

        'contracts.templates.manage' => ['label' => 'Manage Contract Templates', 'group' => 'Contracts'],
        'contracts.send' => ['label' => 'Send Contracts', 'group' => 'Contracts'],
        'contracts.review' => ['label' => 'Review Contracts', 'group' => 'Contracts'],

        'employees.view' => ['label' => 'View Employees', 'group' => 'Employees'],
        'employees.manage' => ['label' => 'Manage Employees', 'group' => 'Employees'],
        'profile_changes.review' => ['label' => 'Review Profile Changes', 'group' => 'Employees'],

        'departments.manage' => ['label' => 'Manage Departments', 'group' => 'Employees'],
        'positions.manage' => ['label' => 'Manage Positions', 'group' => 'Employees'],
        'outlets.manage' => ['label' => 'Manage Outlets', 'group' => 'Employees'],
        'attendance.reports.view' => ['label' => 'View Attendance Reports', 'group' => 'Employees'],
        'training.manage' => ['label' => 'Manage Training', 'group' => 'Training'],
        'appraisals.manage' => ['label' => 'Manage Appraisals', 'group' => 'Appraisal'],
        'notifications.manage' => ['label' => 'Manage Notifications', 'group' => 'General'],

        'finance.view'          => ['label' => 'Lihat Finance Dashboard',    'group' => 'Finance'],
        'finance.import'        => ['label' => 'Import Data Payroll',         'group' => 'Finance'],
        'finance.import.review' => ['label' => 'Review & Konfirmasi Import',  'group' => 'Finance'],
        'finance.bpjs.view'     => ['label' => 'Lihat Data BPJS',            'group' => 'Finance'],
        'finance.bpjs.manage'   => ['label' => 'Kelola Status Bayar BPJS',   'group' => 'Finance'],
        'finance.export'        => ['label' => 'Export Laporan Finance',      'group' => 'Finance'],

        'master.company_groups.manage' => ['label' => 'Kelola Group Perusahaan',      'group' => 'Master Lanjutan'],
        'master.legal_entities.manage' => ['label' => 'Kelola Entitas Legal (PT/CV)', 'group' => 'Master Lanjutan'],
        'master.regions.manage'        => ['label' => 'Kelola Regional & UMR',        'group' => 'Master Lanjutan'],
        'finance.bpjs.rates.manage'    => ['label' => 'Kelola Tarif BPJS per Regional','group' => 'Finance'],
        'finance.bpjs.legal.manage'    => ['label' => 'Kelola Akun Legal BPJS',       'group' => 'Finance'],
        'master.positions.manage'      => ['label' => 'Kelola Master Posisi/Jabatan', 'group' => 'Master Lanjutan'],
    ],

    'legacy_role_permissions' => [
        'admin' => ['*'],
        'finance' => [
            'finance.view',
            'finance.import',
            'finance.import.review',
            'finance.bpjs.view',
            'finance.bpjs.manage',
            'finance.export',
            'finance.bpjs.rates.manage',
            'finance.bpjs.legal.manage',
        ],
        'hrd' => [
            'settings.view',
            'settings.manage',
            'users_roles.manage',
            'applicants.view',
            'applicants.manage',
            'candidates.view',
            'candidates.manage',
            'tests.manage',
            'contracts.templates.manage',
            'contracts.send',
            'contracts.review',
            'employees.view',
            'employees.manage',
            'profile_changes.review',
            'departments.manage',
            'positions.manage',
            'outlets.manage',
            'attendance.reports.view',
            'training.manage',
            'appraisals.manage',
            'notifications.manage',
            'master.company_groups.manage',
            'master.legal_entities.manage',
            'master.regions.manage',
            'master.positions.manage',
        ],
        'manager' => [
            'settings.view',
            'applicants.view',
            'candidates.view',
            'employees.view',
            'appraisals.manage',
            'notifications.manage',
        ],
        'employee' => [],
        'probation' => [],
        'candidate' => [],
        'applicant' => [],
    ],

    'route_permissions' => [
        'dashboard' => ['settings.view'],
        'hrd.dashboard' => ['settings.view'],

        'settings.index' => ['settings.view'],
        'settings.update' => ['settings.manage'],
        'settings.recruitment-retention.*' => ['settings.manage'],

        'hrd.users.*' => ['settings.manage', 'users_roles.manage'],
        'hrd.roles.*' => ['settings.manage', 'users_roles.manage'],
        'hrd.settings.user-roles.*' => ['settings.manage', 'users_roles.manage'],

        'employees.index' => ['employees.view'],
        'employees.show' => ['employees.view'],
        'employees.*' => ['employees.manage'],

        'departments.*' => ['departments.manage'],
        'positions.*' => ['positions.manage'],
        'outlets.*' => ['outlets.manage'],
        'hrd.attendance.*' => ['attendance.reports.view'],
        'hrd.probation-verifications.*' => ['profile_changes.review'],

        'hrd.applicants.index' => ['applicants.view'],
        'hrd.applicants.show' => ['applicants.view'],
        'hrd.applicants.export-pdf' => ['applicants.view'],
        'hrd.applicants.reviewed' => ['applicants.manage'],
        'hrd.applicants.bulk-action' => ['applicants.manage'],
        'hrd.applicants.govern' => ['applicants.manage'],
        'hrd.passed-candidates.*' => ['candidates.view'],

        'candidates.index' => ['candidates.view'],
        'candidates.show' => ['candidates.view'],
        'candidates.profile' => ['candidates.view'],
        'candidates.export-pdf' => ['candidates.view'],
        'candidates.create' => ['candidates.manage'],
        'candidates.store' => ['candidates.manage'],
        'candidates.edit' => ['candidates.manage'],
        'candidates.update' => ['candidates.manage'],
        'candidates.destroy' => ['candidates.manage'],
        'candidates.accept' => ['candidates.manage'],
        'candidates.reject' => ['candidates.manage'],
        'candidates.block' => ['candidates.manage'],
        'candidates.restore' => ['candidates.manage'],
        'candidates.bulk-status' => ['candidates.manage'],
        'candidates.bulk-activate' => ['candidates.manage'],
        'candidates.assessment.update' => ['candidates.manage'],
        'candidates.tests.*' => ['tests.manage'],
        'candidates.bulk-activate-tests' => ['tests.manage'],

        'hrd.contract-templates.*' => ['contracts.templates.manage'],
        'hrd.contracts.index' => ['contracts.review'],
        'hrd.contracts.show' => ['contracts.review'],
        'hrd.contracts.download' => ['contracts.review'],
        'hrd.contracts.review' => ['contracts.review'],
        'hrd.contracts.send' => ['contracts.send'],
        'offering.*' => ['contracts.send'],

        'training-materials.*' => ['training.manage'],
        'hrd.forms.*' => ['tests.manage'],
        'hrd.import.iq.*' => ['tests.manage'],
        'hrd.import.disc.*' => ['tests.manage'],

        'appraisal-periods.*' => ['appraisals.manage'],
        'appraisal-indicators.*' => ['appraisals.manage'],
        'appraisals.index' => ['appraisals.manage'],
        'appraisals.approve' => ['appraisals.manage'],
        'appraisals.assign' => ['appraisals.manage'],
        'appraisals.print' => ['appraisals.manage'],

        'hr-notifications.*' => ['notifications.manage'],

        'master.company-groups.*'    => ['master.company_groups.manage'],
        'master.legal-entities.*'    => ['master.legal_entities.manage'],
        'master.regions.*'           => ['master.regions.manage'],
        'finance.bpjs-rates.*'       => ['finance.bpjs.rates.manage'],
        'finance.bpjs-legal.*'       => ['finance.bpjs.legal.manage'],

        'finance.*'                  => ['finance.view'],
        'finance.import.create'      => ['finance.import'],
        'finance.import.store'       => ['finance.import'],
        'finance.import.row.action'  => ['finance.import.review'],
        'finance.import.confirm-all' => ['finance.import.review'],
        'finance.bpjs.*'             => ['finance.bpjs.view'],
        'finance.bpjs.payment.*'     => ['finance.bpjs.manage'],
    ],
];
