<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\View\View;

class ChangelogController extends Controller
{
    public function index(): View
    {
        return view('changelog.index', [
            'timeline'        => $this->getTimeline(),
            'docs'            => $this->getDocs(),
            'pimpinanReport'  => $this->getPimpinanReport(),
        ]);
    }

    private function getTimeline(): array
    {
        return [
            [
                'version' => 'v3.3.15',
                'date'    => '14 Agustus 2026',
                'label'   => 'Fix Error 500 Halaman Appraisal & Notifikasi, Export Total Gaji Kini Tampilkan Rincian & Rumus',
                'color'   => '#DC2626',
                'items'   => [
                    'Fix error 500 di halaman Penilaian Appraisal (form evaluator) — akar masalahnya bug pada compiler Blade: penulisan kode PHP satu-baris (@php(...)) yang tercampur dengan bentuk blok di file yang sama membuat separuh halaman gagal ter-render. Sudah dirapikan supaya konsisten dan tidak terulang',
                    'Fix error 500 di halaman Settings → Notifikasi — akar masalahnya dua kode perintah Blade yang tertulis nempel tanpa spasi (@endif@endforeach), membuat satu bagian perulangan tidak pernah ditutup dengan benar',
                    'Fix akar masalah deploy: proses build cache tampilan sekarang dijalankan sekali secara terkendali sebelum situs menerima trafik nyata, supaya tidak ada lagi resiko file cache "rebutan tulis" oleh beberapa pengunjung pertama setelah update (yang bisa memicu error 500 sesaat setelah deploy)',
                    'Export Total Gaji per Brand (Finance → Summary Gaji Tahunan → Export Excel) sekarang punya 3 sheet: Total per Outlet (seperti sebelumnya, ditambah jumlah karyawan), Detail per Karyawan (rincian tiap baris sumber: No.Komp, nama, posisi, nilai gaji, file asal import), dan Formula & Sumber Data (rumus SUM/GROUP BY dan sumber tabel secara tertulis) — supaya kalau ada selisih angka dengan perhitungan pimpinan, bisa langsung ditelusuri sampai baris & rumusnya',
                ],
            ],
            [
                'version' => 'v3.3.14',
                'date'    => '12 Agustus 2026',
                'label'   => 'Appraisal: Fix Data Tercampur Antar Periode, Error Perpanjang Due Date, Reminder & Template Email',
                'color'   => '#DC2626',
                'items'   => [
                    'Fix akar masalah data appraisal tercampur antar periode — halaman Monitoring, Laporan, dan Detail Karyawan sebelumnya tidak punya filter periode default sama sekali, jadi appraisal periode berjalan tergabung dengan seluruh riwayat lama (termasuk migrasi Historis MEO) dalam satu angka (mis. muncul 22 evaluator padahal yang diundang cuma 5-6). Sekarang ketiga halaman otomatis menampilkan periode aktif saja secara default — "Semua Periode" tetap bisa dipilih manual kalau perlu lihat riwayat lengkap',
                    'Fix error 500 saat HRD memperpanjang due date appraisal — akar masalahnya kode notifikasi memakai kunci unik berbasis menit, jadi kalau tombol diklik dua kali dalam menit yang sama, terjadi tabrakan data di database. Pola yang sama juga diperbaiki di tombol reminder',
                    'Tombol "Kirim Reminder Evaluator" sekarang dibatasi jeda 24 jam (pakai data terakhir kirim reminder yang sudah ada) — tombol otomatis nonaktif dengan keterangan kapan bisa dikirim lagi, supaya tidak ter-spam tidak sengaja',
                    'Fix akar masalah halaman Settings → Notifikasi (atur judul & isi pesan email per jenis notifikasi) yang ternyata tidak berpengaruh sama sekali ke email appraisal — sekarang template yang diatur HRD di sana benar-benar dipakai saat email terkirim',
                    'Fitur baru: setiap jenis notifikasi appraisal di halaman Settings → Notifikasi sekarang bisa diberi lampiran file (PDF/gambar/dokumen, maks 5MB) yang otomatis ikut terlampir di setiap email jenis itu',
                    'Halaman baru "Panduan Penggunaan" — kumpulan tutorial cara pakai fitur-fitur di atas dalam bahasa sehari-hari untuk HRD, bisa diakses lewat menu Settings → Panduan Penggunaan',
                ],
            ],
            [
                'version' => 'v3.3.13',
                'date'    => '5 Agustus 2026',
                'label'   => 'Appraisal: Skor Tunggal, Tab Kriteria, TTD Dinamis, Notifikasi Email, Shift Outlet',
                'color'   => '#DC2626',
                'items'   => [
                    'Fix akar masalah kriteria penilaian ganda di form evaluator — appraisal lama tanpa template tersimpan sekarang otomatis pakai template sesuai kategori karyawan, bukan menampilkan kriteria dari semua template sekaligus',
                    'Ditemukan & diperbaiki akar masalah yang lebih dalam: template "KRITERIA PENILAIAN OFFICE" dan "KRITERIA OPERASIONAL OUTLET" ternyata belum pernah punya kategori karyawan (lokasi_kerja) terisi sejak dibuat — akibatnya SEMUA appraisal, lama maupun baru, selama ini otomatis jatuh ke template Default. Sekarang appraisal karyawan Office & Operational sudah otomatis pakai kriteria yang benar sesuai kategorinya',
                    'Halaman Kelola Kriteria dirombak jadi tab Office / Operational (menggantikan filter dropdown "Semua Template" yang bikin HRD kebingungan lihat kriteria yang terlihat dobel)',
                    'Komentar evaluator sekarang wajib diisi untuk setiap kriteria yang diberi nilai bintang',
                    'Fix kebingungan angka rata-rata appraisal (79.2 vs 4.18) — ternyata dua sistem skor berbeda dihitung terpisah di 4 tempat kode dengan label klasifikasi yang tidak konsisten. Sekarang satu sumber angka (skala 1-5) dan satu klasifikasi dipakai di semua halaman & export',
                    'Monitoring Appraisal: halaman detail per karyawan sekarang menampilkan evaluator yang belum mengisi (sebelumnya cuma menampilkan yang sudah), lengkap tombol kirim reminder',
                    'Notifikasi appraisal (undangan evaluator, reminder, due date diperpanjang, permintaan edit diajukan/disetujui/ditolak) sekarang juga terkirim ke email evaluator, tidak cuma inbox internal',
                    'Tanda Tangan Digital Appraisal dirombak total: dari 5 slot tetap (Karyawan/HRD/Supervisor/Manager/Director) jadi 3 slot default (Karyawan otomatis + 2 slot kategori bisa diganti HRD) dengan tombol "+ Tambah TTD" sampai maksimal 4. Kategori penanda tangan (PIC/HRD/Manager/Director/Owner In Charge) bisa difilter dari Master Data Posisi. Data tanda tangan lama dipindah otomatis, tidak ada yang hilang',
                    'Ditambahkan kategori "Owner In Charge" untuk tanda tangan — diisi HRD lewat Master Outlet, dipakai untuk owner outlet cabang/franchise yang bukan pengguna sistem',
                    'Fitur baru: Master Shift Kerja per outlet operational — presensi karyawan otomatis dicocokkan ke shift terdekat dari jam scan, bukan selalu memakai satu jam kerja tunggal outlet',
                    'PDF export appraisal: ruang kosong di bagian tanda tangan dirapatkan supaya lebih hemat kertas',
                ],
            ],
            [
                'version' => 'v3.3.12',
                'date'    => '3 Agustus 2026',
                'label'   => 'Cross-Billing BPJS: Sinkronisasi Otomatis Karyawan-PT',
                'color'   => '#DC2626',
                'items'   => [
                    'Relasi karyawan ke PT BPJS (employee_bpjs_assignments) sekarang tersinkron otomatis begitu HRD konfirmasi Review, jalankan ulang matching, atau konfirmasi match manual — tidak perlu lagi jalankan command manual di server setiap upload tagihan baru',
                    'Sinkronisasi selalu insert-only (hanya menambah relasi baru, tidak pernah mengubah/menimpa data yang sudah ada) — aman dijalankan berkali-kali',
                    'Command manual bpjs:backfill-employee-assignments tetap tersedia untuk audit/backfill data lama, kini pakai logika yang sama persis dengan sinkronisasi otomatis supaya hasilnya konsisten',
                    'Pesan konfirmasi di halaman Review/Detail Tagihan menampilkan jumlah relasi karyawan-PT baru yang tercatat, supaya HRD langsung tahu tanpa cek database',
                ],
            ],
            [
                'version' => 'v3.3.11',
                'date'    => '3 Agustus 2026',
                'label'   => 'BPJS: Nama dari Data Karyawan, Email Login, Cross-Billing per PT',
                'color'   => '#DC2626',
                'items'   => [
                    'Fix akar masalah nama/NIK bergeser saat upload tagihan BPJS PDF — nama karyawan di halaman Review sekarang diambil langsung dari data karyawan OMEO berdasarkan NIK, bukan dibaca dari teks PDF yang gampang salah kalau nama panjang/patah 2 baris',
                    'Baris yang NIK-nya belum terdaftar di OMEO ditandai "Belum ada di sistem" dengan jelas, tidak lagi ditebak dari teks PDF',
                    'Fitur baru di halaman Review: edit NIK langsung + tombol tukar NIK dengan baris atas/bawah (▲▼) — begitu NIK diedit/ditukar, sistem otomatis cocokkan ulang ke data karyawan tanpa langkah tambahan',
                    'Fitur baru: tombol "Gabung ke atas" untuk baris nama yang nyasar akibat patah 2 baris di PDF — hanya kolom Nama yang bergeser (seperti geser sel di Excel), NIK dan data lain di setiap baris tetap aman tidak ikut terhapus',
                    'Fix upload Excel BPJS yang sebelumnya error "Row and Column Ids..." — sekarang pesan errornya jelas dan lebih toleran terhadap file hasil convert PDF-ke-Excel',
                    'Fix bug lama: tombol "Re-parse PDF" tidak pernah menjalankan pencocokan NIK ke data karyawan, sehingga tagihan yang di-reparse selalu terlihat "belum ada di sistem" semua walau datanya benar',
                    'Fitur baru: HRD/Admin bisa ubah email login user langsung dari halaman Users & Roles — tidak perlu lagi akses database',
                    'Cross-Billing BPJS: tab "Per PT" sekarang menampilkan kolom "Ditagih ke" — kalau PT penanggung BPJS beda dengan PT payroll asal karyawan, langsung kelihatan PT/outlet mana yang harus ditagih',
                    'Cross-Billing BPJS: command backfill data PT per outlet (berdasarkan daftar resmi dari pimpinan), dengan deteksi otomatis supaya tidak membuat PT duplikat untuk yang sudah tercatat',
                ],
            ],
            [
                'version' => 'v3.3.10',
                'date'    => '30 Juli 2026',
                'label'   => 'Appraisal: Monitoring per Karyawan, Koreksi Nilai, Print Out PDF',
                'color'   => '#0891B2',
                'items'   => [
                    'Command backfill: histori appraisal lama otomatis dikonversi ke klasifikasi 6-tingkat baru (Outstanding/dst)',
                    'Fix tombol "Print Out" di Laporan Appraisal per karyawan — sekarang buka file PDF rapi (sama seperti Export PDF) di tab baru, bukan cetak halaman HTML mentah',
                    'Redesign halaman Monitoring Appraisal: 1 baris = 1 karyawan (gabungan semua evaluator), progress ditampilkan sebagai "X/Y evaluator submit", klik Detail untuk kelola per evaluator',
                    'Filter baru di Monitoring: nama/jabatan/NIK, departemen, status agregat (Selesai Semua/Sebagian/Belum Ada), due date terlewat, jenis trigger',
                    'Fitur baru: HRD bisa perpanjang due date untuk semua evaluator satu karyawan sekaligus (bukan cuma satu-satu) dari halaman Laporan Appraisal per karyawan',
                    'Fitur baru: HRD bisa exclude penilaian evaluator tertentu dari perhitungan rata-rata gabungan (misal evaluator salah kasih nilai), tanpa hapus datanya, bisa di-include lagi kapan saja',
                    'Fitur baru: evaluator bisa ajukan izin edit ulang penilaian yang sudah di-approve HRD (wajib isi alasan), HRD approve/reject, maksimal 2x per appraisal, dibatasi due date, dengan reminder ke kedua sisi',
                ],
            ],
            [
                'version' => 'v3.3.9',
                'date'    => '30 Juli 2026',
                'label'   => 'Appraisal: Perpanjang Due Date, Skor Gaya IPK, Template Kriteria per Kategori',
                'color'   => '#7C3AED',
                'items'   => [
                    'Fitur baru: HRD/Admin bisa perpanjang due date appraisal langsung dari halaman detail (dengan alasan wajib diisi), tercatat otomatis di Audit Trail Invitation',
                    'Klasifikasi hasil penilaian diganti dari 5-tingkat lama ke 6-tingkat gaya IPK: Outstanding, Exceed Expectation, Above Expectation, Meet Expectation, Need Improvement, Unsatisfactory (4.51-5.00 s.d. <2.50)',
                    'Fitur baru: halaman "Panduan Skor Penilaian" — berisi prinsip penilaian evaluator, tabel klasifikasi 6-tingkat, dan panduan umum skor 1-5, bisa diakses evaluator sebelum menilai',
                    'Form penilaian evaluator kini menampilkan banner pengingat panduan skor + link ke halaman panduan lengkap',
                    'Fitur baru: tiap kriteria penilaian bisa punya keterangan khusus per skor (1-5) — muncul otomatis sebagai tooltip saat evaluator arahkan kursor ke bintang',
                    'Fitur baru: Template Kriteria Appraisal — HRD bisa buat kumpulan kriteria berbeda per kategori karyawan (Office / Operational Outlet / Production), sistem otomatis pilih template yang sesuai berdasarkan data karyawan, lengkap dengan tombol duplikat template supaya tidak perlu input ulang dari nol',
                ],
            ],
            [
                'version' => 'v3.3.8',
                'date'    => '27 Juli 2026',
                'label'   => 'Slip Gaji Karyawan',
                'color'   => '#059669',
                'items'   => [
                    'Fitur baru: halaman Slip Gaji — pilih periode, cari karyawan, lihat/unduh slip gaji dalam format PDF',
                    'Slip gaji berisi rincian Pendapatan (Gaji Pokok, Tunjangan, Uang Hadir, HR, Lembur, S.Expense) dan Potongan (BPJS Ketenagakerjaan, BPJS Kesehatan, Potongan Lain), serta Take Home Pay',
                    'Nomor rekening bank karyawan otomatis tampil di slip kalau sudah terdaftar di data karyawan',
                    'Karyawan yang kerja di lebih dari 1 outlet dalam periode yang sama otomatis dijumlahkan, kecuali difilter ke 1 outlet spesifik',
                    'Tombol "Preview" untuk lihat slip di tab baru tanpa langsung terunduh, dan tombol "Unduh" terpisah untuk yang memang mau simpan file-nya',
                ],
            ],
            [
                'version' => 'v3.3.7',
                'date'    => '27 Juli 2026',
                'label'   => 'BPJS Parser Fix & Export PDF Bulk Appraisal',
                'color'   => '#B45309',
                'items'   => [
                    'Fix BPJS PDF Parser: tagihan multi-halaman (mis. PT Imperial Prima Food, 34 karyawan) sebelumnya salah baca nilai iuran untuk SEMUA karyawan (bukan cuma yang di halaman terakhir) karena filter "buang grand total" salah membuang kolom Upah, JHT Pemberi Kerja, dan Total Iuran yang sah',
                    'Fix BPJS PDF Parser: filter grand total sekarang hanya aktif kalau memang ada indikasi data belum rapi, supaya tidak salah membuang kolom yang sah lagi di kemudian hari',
                    'Fitur baru: tombol "Export PDF Semua" di halaman Laporan Appraisal — gabungkan laporan detail (matriks penilaian, narasi, keputusan) semua karyawan sesuai filter ke dalam 1 file PDF, satu bagian per karyawan',
                ],
            ],
            [
                'version' => 'v3.3.6',
                'date'    => '27 Juli 2026',
                'label'   => 'Sprint I & K: BPJS Cross-Billing dan Penugasan Outlet',
                'color'   => '#0891B2',
                'items'   => [
                    'Master Departemen: 4 departemen duplikat digabung ke departemen resmi (HRGA, Finance Accounting, Purchasing, Marketing), 6 unit operasional (Bar, Kitchen Outlet, Kitchen Production, Office Production, Service, Maintenance) ditata di bawah Departemen Operational',
                    'Master Departemen: validasi nama unik ditambahkan supaya tidak terjadi duplikat baru di kemudian hari',
                    'BPJS: PT/badan hukum kini otomatis terdeteksi dari NPP di file tagihan BPJS yang diupload — tidak perlu isi master PT secara manual lagi',
                    'BPJS: riwayat kepesertaan BPJS karyawan (employee_bpjs_assignments) di-backfill otomatis dari data tagihan yang sudah direkonsiliasi',
                    'Fix Laporan Cross-Billing BPJS: nominal iuran yang sebelumnya tampil Rp 0 karena format No.Komp beda antara data payroll dan data karyawan',
                    'Fix Laporan Cross-Billing BPJS: karyawan multi-outlet sempat terhitung dobel di laporan, sekarang sudah akurat',
                    'Fitur baru: Laporan Cross-Billing BPJS per Outlet — menampilkan outlet mana yang membayar BPJS untuk karyawan dari outlet lain, dan outlet asal yang seharusnya ditagih',
                    'Master Outlet: field PT/Badan Hukum ditambahkan supaya tiap outlet bisa ditandai badan hukum BPJS-nya',
                    'Fitur baru: riwayat penugasan outlet & departemen karyawan (rolling/multi-outlet), otomatis terisi dari data payroll yang sudah diimport',
                    'Fix 4 outlet yang belum terdaftar di Master Outlet — otomatis dibuat dari data payroll supaya tidak ada lagi transaksi payroll yang tidak ter-mapping ke outlet',
                    'Fix judul PDF export Rekap Presensi yang salah menampilkan nama karyawan tidak sesuai filter yang dipilih',
                    'Fitur baru: PDF export Rekap Presensi kini per-karyawan satu halaman sendiri, tidak lagi tercampur dalam satu tabel panjang',
                    'Fix halaman Struktur Organisasi (Org Chart) yang gagal total (error 500) karena konflik penamaan kode antara Blade dan Alpine.js',
                ],
            ],
            [
                'version' => 'v3.3.5',
                'date'    => '22 Juli 2026',
                'label'   => 'Annual Summary Export Fix',
                'color'   => '#059669',
                'items'   => [
                    'Fix filter outlet tidak bekerja di sheet SUMMARY DETAIL: sebelumnya data semua outlet ikut masuk meski sudah difilter',
                    'Fix total salah: sebelumnya hanya hitung 4 komponen (Gaji Pokok + Attd + HR + S.Expense), sekarang menggunakan total lengkap dari CSV payroll termasuk OT dan Tunjangan',
                    'Fix karyawan yang seharusnya muncul tidak muncul (Septian, Friska, Eko, Mahrus, dll): sumber data SUMMARY DETAIL diganti dari payroll_annual_summaries ke finance_bpjs_records langsung',
                    'Fix Sugiyanto dan karyawan multi-outlet: data bulan per bulan sekarang difilter per outlet sehingga tidak lagi menggabungkan gaji dari semua outlet',
                    'Tambah kolom NIK di sheet per bulan dan SUMMARY DETAIL',
                    'Fix NIK tampil sebagai E+15 (scientific notation): NIK 16 digit sekarang ditampilkan sebagai teks penuh',
                    'Fix No.Komp hilang leading zero: 004278 tidak lagi menjadi 4278 di Excel',
                    'Fix 27 outlet MKO dan QUALI dengan outlet_id NULL: 4.695 records finance_bpjs_records berhasil di-mapping ke outlet yang benar sehingga filter outlet bekerja untuk semua outlet MKO dan QUALI',
                    'NIK diambil dari tabel employees via join no_komp = employee_number (bukan dari finance_bpjs_records yang NULL)',
                ],
            ],
            [
                'version' => 'v3.3.4',
                'date'    => '21 Juli 2026',
                'label'   => 'KPI Bobot Formula Setting',
                'color'   => '#059669',
                'items'   => [
                    'Halaman baru "Bobot Formula Appraisal" — HRD dapat mengatur sendiri persentase kontribusi setiap komponen tanpa bantuan programmer',
                    'Setting 2 level: Global (fallback untuk semua tipe) dan Per-Tipe (Probation / Annual Review / Contract Renewal)',
                    '5 komponen yang dapat diatur bobotnya: Kriteria Bintang, KPI, Training, Kompetensi Skill, Kompetensi Posisi',
                    'Live preview rumus aktif: "Kriteria 50% + KPI 30% + Training 20% = 100%" — realtime saat angka diubah',
                    'Validasi ketat: tombol Simpan hanya aktif jika total bobot = 100%',
                    'Setting per-tipe otomatis override setting global; tombol "Hapus / Gunakan Global" untuk reset ke default',
                    'Formula scoring appraisal kini dinamis — membaca bobot dari database, bukan hardcoded di kode',
                    'Komponen Skill dan Posisi kini masuk perhitungan final score jika bobotnya > 0%',
                    'Audit trail: tampil nama dan waktu terakhir HRD mengubah setting',
                    'Menu "Bobot Formula Appraisal" ditambahkan ke sidebar grup Appraisal HRD',
                ],
            ],
            [
                'version' => 'v3.3.3',
                'date'    => '21 Juli 2026',
                'label'   => 'Migrasi Data Historis MEO',
                'color'   => '#7C3AED',
                'items'   => [
                    'Migrasi 136 data appraisal historis dari aplikasi MEO lama ke OMEO secara otomatis via Artisan command',
                    'Data mencakup 19 karyawan dengan periode penilaian Agustus 2025 hingga Juli 2026',
                    'Konversi skala otomatis: skor MEO (1-4) dikonversi proporsional ke skala OMEO (1-5 → 100)',
                    'Karyawan resign (Robby, Raymond Antonius) otomatis di-skip, tidak dibuatkan data baru di OMEO',
                    'Badge "📂 Historis MEO" muncul di halaman laporan untuk membedakan data lama vs data baru',
                    'Artisan command: php artisan appraisal:migrate-from-meo dengan opsi --dry-run untuk preview sebelum eksekusi',
                    'Cross-database query langsung dari sql_omeo ke meo_mykopio tanpa perlu export/import file',
                ],
            ],
            [
                'version' => 'v3.3.2',
                'date'    => '20 Juli 2026',
                'label'   => 'Appraisal Report & Privacy Fix',
                'color'   => '#0369A1',
                'items'   => [
                    'Halaman Laporan Appraisal baru: monitoring semua karyawan yang sedang atau sudah di-appraisal dalam satu halaman',
                    'Laporan dikelompokkan per karyawan (bukan per appraisal) — klik nama untuk expand dan lihat detail per evaluator',
                    'Kolom: Nama, Periode, Jumlah Evaluator, Rata-rata Skor, Hasil, Status, dengan sort dan search realtime',
                    'Privacy fix: karyawan yang dinilai tidak dapat melihat nama evaluator, hanya "Evaluator 1", "Evaluator 2" dst',
                    'Privacy fix: invitation_note dan probation_end_snapshot tidak lagi bocor ke tampilan karyawan',
                    'Fix KPI scoring: jika komponen KPI dinonaktifkan, skor dihitung ulang secara proporsional dari komponen lain (bukan stuck di max 70%)',
                    'Dynamic weight normalization: skor final selalu ternormalisasi ke skala 100 meski ada komponen yang dinonaktifkan',
                    'Slot tanda tangan batch: sistem tanda tangan per batch appraisal untuk laporan formal',
                ],
            ],
            [
                'version' => 'v3.3.1',
                'date'    => '14 Juli 2026',
                'label'   => 'BPJS Cross-billing & Parser Upgrade',
                'color'   => '#B45309',
                'items'   => [
                    'BPJS PDF Parser: fix nama terfragmentasi multi-baris (contoh: "KHALIFA AURELIA NUR HIDAYAT" tidak lagi terpecah)',
                    'BPJS PDF Parser: fix grand total row tidak ikut terhitung sebagai data karyawan (filter outlier N × median × 0.3)',
                    'BPJS PDF Parser: fix PDF multi-halaman — halaman 2 dst dipotong di marker "Jumlah Seluruhnya" sebelum parsing',
                    'BPJS XLSX Importer: support format Kopijaya Prima Food (28 kolom, NIK di kolom D, total di kolom AA)',
                    'BPJS XLSX Importer: fix NIK 16-digit yang tersimpan sebagai float di Excel tidak lagi kehilangan 2 digit terakhir',
                    'Halaman Review Nama (Step 2): edit nama inline setelah upload PDF/XLSX sebelum rekonsiliasi dijalankan',
                    'Tombol Re-parse PDF: re-parse dengan algoritma terbaru tanpa upload ulang file',
                    'Cross-billing BPJS: rekap karyawan per outlet yang ditanggung satu PT namun tersebar di outlet PT lain',
                    'Cross-billing: accordion per outlet dengan jumlah karyawan + total iuran + daftar nama lengkap',
                    'Cross-billing: summary card clickable → modal popup berisi daftar nama per kategori (✓ Juni / 📅 Periode Lain / ⚠️ Perlu Cek / ✗ Belum di Payroll CSV)',
                    'Cross-billing: multi-session lookup (cari di semua periode payroll jika tidak ditemukan di periode aktif)',
                    'Cross-billing: export Excel per outlet (sheet terpisah per outlet + sheet rekap)',
                    'Cross-billing: warning otomatis jika nama BPJS berbeda dengan nama di payroll (perlu verifikasi HRD)',
                ],
            ],
            [
                'version' => 'v3.3.0',
                'date'    => '13 Juli 2026',
                'label'   => 'Positions & Org Chart',
                'color'   => '#0369A1',
                'items'   => [
                    'Master Posisi & Departemen: CRUD lengkap dengan import/export Excel, template panduan level hierarki (L1–L10)',
                    'Migrasi 1.834 karyawan ke FK position_id & department_id (dari jabatan varchar ke relasi terstruktur)',
                    'Org Chart visual interaktif: grid departemen + card posisi, klik posisi → panel slide kanan berisi daftar karyawan',
                    'Panel org chart: foto profil karyawan, search real-time, badge level, status probation/permanent/contract',
                    'Seed otomatis 13 posisi dari jabatan existing + 10 departemen dari data legacy perusahaan',
                ],
            ],
            [
                'version' => 'v3.2.2',
                'date'    => '13 Juli 2026',
                'label'   => 'Notifikasi Smart Filter',
                'color'   => '#7C3AED',
                'items'   => [
                    'Notifikasi kini bersifat personal — karyawan biasa hanya melihat notifikasi yang memang ditujukan untuk mereka, tidak lagi melihat notifikasi internal HRD',
                    'Tab filter per tipe notifikasi: Kontrak Karyawan, Appraisal, Reminder, Perubahan Profil, dan lainnya — dengan badge jumlah unread per tipe',
                    'Filter rentang tanggal pada halaman inbox notifikasi (dari tanggal — hingga tanggal)',
                    'Bell icon dropdown menampilkan preview 5 notifikasi terbaru dengan icon dan label per tipe',
                    'Badge unread di bell icon hanya menghitung notifikasi yang relevan untuk user yang sedang login',
                    'Probation reminder kini dikirim spesifik ke HRD/admin, tidak lagi broadcast ke seluruh 1851 user',
                ],
            ],
            [
                'version' => 'v3.2.1',
                'date'    => '12 Juli 2026',
                'label'   => 'Walk-in Auto-sort & Antrian per Posisi',
                'color'   => '#059669',
                'items'   => [
                    'Walk-in Dashboard: Tab antrian otomatis per posisi yang dilamar kandidat (COOK, BAR, SERVICE, KASIR, dll)',
                    'Nomor antrian per posisi urut sesuai waktu check-in, tampil sebagai badge lingkaran ungu di tabel',
                    'Badge jumlah hadir vs total per posisi di setiap tab (contoh: 2/3 artinya 2 hadir dari 3 pendaftar)',
                    'Kandidat yang belum check-in tetap tampil di tab posisinya tanpa nomor antrian',
                    'Status kandidat (Hadir/Menunggu/No-show) ditampilkan dengan badge warna di setiap tab posisi',
                    'Sub-total hadir per posisi di footer tabel',
                ],
            ],
            [
                'version' => 'v3.2.0',
                'date'    => '11 Juli 2026',
                'label'   => 'Sprint I — BPJS Cross-billing & Finance Enhancements',
                'color'   => '#0891b2',
                'items'   => [
                    // ── Fitur Baru ──
                    'BPJS Assignment (Master Data Karyawan Rolling): HRD bisa mencatat karyawan yang BPJS-nya ditanggung PT berbeda dari tempat kerjanya. Tersedia di menu Master BPJS → BPJS Assignment. Mendukung tambah manual dan import bulk via Excel.',
                    'Import & Template BPJS Assignment: Upload Excel untuk assign banyak karyawan sekaligus ke PT BPJS yang menanggung. Template menyertakan daftar PT valid di Sheet 2.',
                    'Laporan Cross-billing BPJS: Halaman baru menampilkan karyawan rolling per PT beserta nominal iuran (BPJS TK Pekerja, BPJS TK Perusahaan, BPJS JKES, Total Iuran). Filter per PT dan per periode. Export Excel per PT — setiap PT mendapat sheet tersendiri.',
                    'Template Transfer Bank Mandiri (XLSX & CSV): Finance bisa download template transfer gaji format MCM 2.0 dari halaman Summary Gaji Tahunan. Tersedia 2 format (Excel dan CSV). Keterangan kolom H bisa diisi bebas sebelum download.',
                    'Export Total Gaji per Outlet: Tombol baru di dropdown Export Excel pada halaman Summary Gaji Tahunan. Download rekap total gaji per outlet/brand untuk periode yang dipilih.',
                    'Rekening Bank Karyawan: HRD bisa kelola data rekening bank karyawan di tab Payroll pada profil karyawan. Support multi-rekening dengan penanda PRIMARY.',
                    // ── Perbaikan ──
                    'Profil Karyawan HRD Lebih Lengkap: Tab Training menampilkan riwayat pelatihan dan persentase progress. Dokumen tambahan (ijazah, transkrip, akta lahir) kini tampil di profil karyawan.',
                    'NIK Karyawan Sinkron Otomatis: NIK yang diisi kandidat saat mendaftar otomatis tersalin ke profil karyawan saat diterima. Tampilan NIK di daftar karyawan diperbaiki dengan fallback ke applicant profile.',
                    'Rekap Presensi — Filter Rentang Tanggal: Filter HRD kini mendukung rentang tanggal (dari–hingga). Export PDF menyesuaikan rentang yang dipilih. Filter preset (Harian/Mingguan/Bulanan) tetap tersedia.',
                    'Form Pendaftaran Kandidat — Tidak Memblokir: Upload dokumen (SKCK, ijazah, transkrip, akta) tidak lagi saling memblokir. File yang sudah diupload tidak hilang saat berpindah step. Submit bisa dilakukan meski dokumen belum lengkap, disertai banner pengingat.',
                    'Parser Rekonsiliasi BPJS Lebih Akurat: Fix 2 bug — (1) nama karyawan panjang yang terpecah jadi 2 entri oleh PDF parser kini digabung otomatis, (2) baris "Jumlah Seluruhnya" tidak lagi terhitung sebagai iuran karyawan pertama.',
                    'Appraisal — Final Result & Proposed Appraisal: Final Result tampil otomatis sebagai badge kalkulasi. Dropdown Proposed Appraisal tersedia: RE CONTRACT / DISCONTINUE / PROMOTED / PERMANENT WORKER / POSITION CHANGE / PENDING.',
                    // ── Teknis ──
                    'Migration baru: fix_employee_assignments_missing_columns, add_rekening_flag_to_payroll_import_rows, create_employee_bank_accounts_table.',
                    'Artisan commands baru: employee:sync-nik (sinkron NIK dari applicant profile), payroll:fix-rekening (recovery nomor rekening scientific notation).',
                ],
            ],
            [
                'version' => 'v3.0.0',
                'date'    => '30 Juni 2026',
                'label'   => 'Assignment Appraisal — Kanban 3 Kolom + Batch Builder',
                'color'   => '#7c3aed',
                'items'   => [
                    'Kandidat probation ditampilkan dalam 3 kolom Kanban: Masih Aman (>7 hari), Segera ≤7 hari, Sudah Lewat — prioritas visual langsung terlihat',
                    'Batch Builder: pilih evaluator berbeda per karyawan dalam satu sesi, lalu generate semua draft appraisal sekaligus',
                    'Status probation dihitung otomatis dari Join Date + 3 bulan (karena 99,9% data HRIS lama masih default "probation")',
                    'Fix live search karyawan & evaluator: root cause BOM tersembunyi di 2 file konfigurasi yang merusak setiap JSON response',
                    'Walk-In Interview Phase 2: update status interview, input hasil tes, dan plotting outlet kini tersedia di halaman detail kandidat',
                ],
            ],
            [
                'version' => 'v9.2',
                'date'    => 'Juni 2026',
                'label'   => 'Sprint L — Redesign Appraisal Scoring',
                'color'   => '#f97316',
                'items'   => [
                    'Redesign form scoring: KPI 30% (persentase 0-100), Training 20% (multi-entry), Kriteria 50% (bintang 1-5)',
                    'Star rating 5 bintang menggantikan input angka untuk 11 kriteria evaluasi',
                    'Input KPI single percentage field — lebih sederhana dari komponen terpisah sebelumnya',
                    'Training multi-entry: tabel dinamis Alpine.js untuk input nilai beberapa materi training',
                    '3-mode assignment: Probation (filter periode), Manual (pencarian bebas), Semua Karyawan',
                    'Live search employee & evaluator via Alpine.js AJAX — tanpa reload halaman',
                    '11 indikator penilaian dengan bobot total 100 (3 Kompetensi Kerja, 4 Karakter, 3 Sikap, 1 Kehadiran)',
                    'Fix duplikat indikator: seeder truncate sebelum insert dengan FK guard',
                ],
            ],
            [
                'version' => 'v9.1',
                'date'    => 'Juni 2026',
                'label'   => 'Sprint K — Tab Penugasan Karyawan',
                'color'   => '#6366f1',
                'items'   => [
                    'Tab baru "Penugasan" di halaman detail karyawan',
                    'Model EmployeeAssignment dengan dual-column compatibility (effective_date / start_date)',
                    'Controller CRUD: store dengan auto-close penugasan aktif sebelumnya, destroy dengan guard',
                    'Modal tambah penugasan dengan pilihan outlet, cost center, entitas legal, departemen, tipe, alasan',
                    'Badge aktif di sidebar karyawan: Outlet Tugas, Cost Center, Entitas Legal',
                    'Accessor effective_date_display, is_active, assignment_type_label',
                ],
            ],
            [
                'version' => 'v9.0',
                'date'    => 'Juni 2026',
                'label'   => 'Sprint J — Rekonsiliasi Payroll vs BPJS PDF',
                'color'   => '#0ea5e9',
                'items'   => [
                    'Halaman rekonsiliasi baru: payroll CSV vs tagihan BPJS PDF',
                    'Matching 3-level cascade: employee_id → NIK → nama exact',
                    'Status otomatis: Cocok / Selisih Minor / Selisih / Tidak di Payroll / Tidak di BPJS',
                    'Filter periode, PT, status; stats cards 5 warna',
                    'Export Excel via PhpSpreadsheet',
                    'Multi-upload PDF BPJS dengan drag-and-drop Alpine.js dan file preview',
                    'Fix 500 error pada Jalankan Rekonsiliasi: try-catch + guard employee_id null',
                ],
            ],
            [
                'version' => 'v8.5',
                'date'    => 'Mei 2026',
                'label'   => 'LMS & My Training Overhaul',
                'color'   => '#10b981',
                'items'   => [
                    'LmsService: tableCache guard, syncEnrollmentForEmployee single-employee mode',
                    'MyTrainingController: fallback 3-level employee matching (employee_id → email → nama)',
                    'Command omeo:link-users-employees --dry-run untuk batch auto-link user ke karyawan',
                    'Fix Storage::disk url + auth()->user()?->id untuk kompatibilitas IDE',
                ],
            ],
            [
                'version' => 'v8.0',
                'date'    => 'April 2026',
                'label'   => 'BPJS Rekonsiliasi & Finance Module',
                'color'   => '#f59e0b',
                'items'   => [
                    'BpjsReconciliationController + Service: parse PDF tagihan BPJS',
                    'Tabel finance_bpjs_records dengan data iuran per karyawan',
                    'Detail rekonsiliasi per bill: tabel baris, status per karyawan',
                    'Sidebar Finance: menu Rekap BPJS dan Rekon BPJS vs Payroll',
                ],
            ],
            [
                'version' => 'v7.0',
                'date'    => 'Maret 2026',
                'label'   => 'Appraisal & Attendance',
                'color'   => '#ec4899',
                'items'   => [
                    'Modul appraisal: period, indicator, assignment, self-assessment, evaluator review',
                    'Attendance check-in/out dengan geolocation',
                    'Laporan kehadiran HRD: filter per outlet, export CSV',
                    'Notifikasi HR in-app: inbox, badge unread',
                ],
            ],
            [
                'version' => 'v6.0',
                'date'    => 'Februari 2026',
                'label'   => 'Training Program & LMS',
                'color'   => '#8b5cf6',
                'items'   => [
                    'Training programs, materials (video/PDF/link), eligibility scope',
                    'Pre-test & post-test per material',
                    'Trainer management + event registration',
                    'My Training portal untuk karyawan: progress, sertifikat',
                ],
            ],
            [
                'version' => 'v5.0',
                'date'    => 'Januari 2026',
                'label'   => 'Recruitment & Onboarding',
                'color'   => '#ef4444',
                'items'   => [
                    'Job postings, career portal publik, walk-in interview',
                    'Applicant pipeline: form, tes IQ/DISC, offering, contract',
                    'Probation onboarding checklist',
                    'Daily worker contract template builder',
                ],
            ],
        ];
    }

    private function getDocs(): array
    {
        return [
            [
                'category' => 'Arsitektur',
                'icon'     => 'M3 3h18v4H3zM3 10h18v4H3zM3 17h18v4H3z',
                'color'    => '#6366f1',
                'articles' => [
                    [
                        'title' => 'Struktur Route',
                        'body'  => 'Aplikasi memiliki dua file route utama: <code>routes/web.php</code> untuk modul Finance (prefix <code>/finance</code>, middleware <code>auth</code>), dan <code>routes/hr_suite_v6.php</code> untuk semua modul HRD. Route HRD dibagi dalam grup middleware: <code>auth</code> (semua user), <code>role:admin,hrd,manager</code> (HRD), dan <code>role:admin</code> (admin only).',
                    ],
                    [
                        'title' => 'Sidebar Menu',
                        'body'  => 'Menu sidebar di <code>resources/views/partials/hr_suite_menu.blade.php</code> menggunakan helper <code>$routeItem(route_name, label, icon_key)</code>. Icon tersedia: employee, candidate, folder, report, settings, reconcile, bpjs, finance, attendance, department, outlet, dll. Tambahkan item ke array grup yang sesuai (<code>$hrdCore</code>, <code>$financeCore</code>, <code>$settings</code>, dll).',
                    ],
                    [
                        'title' => 'Schema Guard Pattern',
                        'body'  => 'Gunakan <code>Schema::hasTable(\'nama_tabel\')</code> sebelum query ke tabel yang mungkin belum dimigrasikan di server lain. Pola: <code>Schema::hasTable(\'x\') ? Model::query()... : collect()</code>. Ini mencegah 500 error saat tabel belum ada.',
                    ],
                ],
            ],
            [
                'category' => 'Finance & BPJS',
                'icon'     => 'M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm1 15h-2v-4H9l3-3 3 3h-2v4z',
                'color'    => '#0ea5e9',
                'articles' => [
                    [
                        'title' => 'Kolom Tabel finance_bpjs_records',
                        'body'  => 'Kolom utama: <code>no_komp</code>, <code>nama</code>, <code>outlet_name</code>, <code>bpjs_tk_employee</code>, <code>bpjs_jkes_employee</code>. Tidak ada kolom <code>total</code> — gunakan <code>SUM(bpjs_tk_employee + bpjs_jkes_employee)</code> untuk total iuran.',
                    ],
                    [
                        'title' => 'Kolom Tabel bpjs_official_bills',
                        'body'  => 'Kolom nama file: <code>source_file_name</code> (bukan <code>file_name</code>). Kolom periode: <code>periode</code> format <code>YYYY-MM</code>. Relasi ke <code>bpjs_official_bill_rows</code> via <code>bill_id</code>.',
                    ],
                    [
                        'title' => 'Matching Logic Rekonsiliasi',
                        'body'  => 'Matching 3-level cascade: (1) <code>employee_id</code> → <code>empMap</code> (employee_id → no_komp stripped), (2) NIK stripped spaces → <code>empByNik</code> (nik → employee_number), (3) nama exact match ke <code>finance_bpjs_records.nama</code>. Pre-load kedua map dengan single query <code>whereIn</code> sebelum loop untuk hindari N+1.',
                    ],
                ],
            ],
            [
                'category' => 'Employee & Assignment',
                'icon'     => 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z',
                'color'    => '#10b981',
                'articles' => [
                    [
                        'title' => 'Dual-Column Compatibility (start_date / effective_date)',
                        'body'  => 'Tabel <code>employee_assignments</code> di server lama punya <code>start_date</code>, server baru punya <code>effective_date</code>. Solusi: keduanya ada di <code>$fillable</code> dan <code>$casts</code>. ORDER BY menggunakan <code>COALESCE(effective_date, start_date)</code>. Di view gunakan accessor <code>effective_date_display</code> bukan direct property.',
                    ],
                    [
                        'title' => 'Employee Outlet Fields',
                        'body'  => 'Model Employee punya dua outlet FK: <code>outlet_id</code> (outlet utama/BPJS) dan <code>outlet_penugasan_id</code> (outlet penugasan). Enum <code>outlet_type</code>: <code>branch</code>, <code>central_kitchen</code>, <code>office</code>, <code>virtual</code>.',
                    ],
                    [
                        'title' => 'Auto-Close Assignment',
                        'body'  => 'Saat store assignment baru, controller otomatis menutup semua penugasan aktif sebelumnya: <code>whereNull(\'end_date\')->where(\'effective_date\', \'<\', $newDate)->update([\'end_date\' => $newDate])</code>. Dibungkus dalam <code>DB::transaction()</code>.',
                    ],
                ],
            ],
            [
                'category' => 'Frontend & UI',
                'icon'     => 'M4 6h16M4 12h16M4 18h7',
                'color'    => '#f59e0b',
                'articles' => [
                    [
                        'title' => 'Tailwind JIT & Dynamic Classes',
                        'body'  => 'Tailwind JIT tidak bisa scan class yang dibuat secara dinamis di PHP loop (contoh: <code>"bg-{$color}-100"</code>). Solusi: gunakan inline <code>style=""</code> untuk semua warna dinamis. Hanya class statis yang aman dipakai langsung.',
                    ],
                    [
                        'title' => 'Alpine.js Patterns',
                        'body'  => 'Tab navigation: <code>x-data="{ tab: \'default\' }"</code> + <code>x-show="tab === \'x\'"</code>. Modal: <code>x-data="{ show: false }"</code> + <code>@click.outside="show = false"</code>. File preview multi-upload: <code>x-data="{ files: [] }"</code> dengan <code>@change="files = [...$event.target.files]"</code> dan drag-drop handlers.',
                    ],
                    [
                        'title' => 'Layout Base',
                        'body'  => 'Semua halaman HRD menggunakan <code>@extends(\'layouts.app\')</code> dengan <code>@section(\'title\')</code> dan <code>@section(\'content\')</code>. Konten dibungkus <code>&lt;div class="p-6"&gt;</code>. Sidebar dimuat otomatis dari partial <code>hr_suite_menu.blade.php</code>.',
                    ],
                ],
            ],
            [
                'category' => 'Appraisal HRD',
                'icon'     => 'M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 0 0 .95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 0 0-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 0 0-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 0 0-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 0 0 .951-.69l1.519-4.674z',
                'color'    => '#ec4899',
                'articles' => [
                    [
                        'title' => 'Generate Appraisal — Mode Probation',
                        'body'  => 'Mode <code>probation</code> otomatis mengambil karyawan yang <code>join_date</code>-nya dalam window ±30 hari dari hari ini. HRD tinggal centang nama dan klik Generate. Trigger appraisal di-set ke <code>probation_timeline</code>.',
                    ],
                    [
                        'title' => 'Generate Appraisal — Mode Manual',
                        'body'  => 'Mode <code>manual</code> menyediakan live search Alpine.js untuk cari karyawan dan evaluator. Ketik min 2 karakter, hasil muncul real-time via AJAX ke route <code>appraisals.assignment.search-employees</code>. Trigger default: <code>manual_acceleration</code>.',
                    ],
                    [
                        'title' => 'Form Evaluasi: KPI + Training + Kriteria',
                        'body'  => 'Skor akhir (0-100) = KPI 30% + Training 20% + Rata-rata bintang 50%. KPI diisi sebagai persentase (0-100). Training sebagai tabel multi-entry nilai per materi (avg dihitung otomatis). Kriteria 11 item diberi bintang 1-5, dikonversi ke 0-100 via ×20.',
                    ],
                    [
                        'title' => 'Monitoring & Approval Appraisal',
                        'body'  => 'Status appraisal: <code>draft</code> → <code>self_assessment</code> → <code>evaluator_review</code> → <code>approved</code>. HRD bisa lihat semua appraisal di halaman index dengan filter status, periode, dan outlet. Approval mengubah status ke <code>approved</code> dan menyimpan <code>final_score</code>.',
                    ],
                    [
                        'title' => 'Lihat Hasil Karyawan',
                        'body'  => 'Karyawan dapat melihat hasil appraisal mereka (jika status sudah <code>approved</code>) di portal self-service. HRD dapat mencetak/export hasil appraisal individual. Final result label (skala bintang 1-5, gaya IPK): 4.51-5.00 Outstanding, 4.01-4.50 Exceed Expectation, 3.51-4.00 Above Expectation, 3.00-3.50 Meet Expectation, 2.50-2.99 Need Improvement, &lt;2.50 Unsatisfactory.',
                    ],
                ],
            ],
            [
                'category' => 'LMS & Training',
                'icon'     => 'M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z',
                'color'    => '#8b5cf6',
                'articles' => [
                    [
                        'title' => 'Employee Matching di LMS',
                        'body'  => 'LmsService dan MyTrainingController menggunakan fallback 3-level untuk link user ke karyawan: (1) <code>users.employee_id</code> sudah ada, (2) match via <code>email</code> → <code>email_private</code>, (3) match via <code>name</code> → <code>full_name</code>. Setiap match yang berhasil auto-update <code>users.employee_id</code>.',
                    ],
                    [
                        'title' => 'Enrollment Sync',
                        'body'  => 'LmsService mendukung dua mode sync: bulk (<code>ensureAllEnrollments()</code>) dan single-employee (<code>syncEnrollmentForEmployee($employeeId)</code>). Gunakan single-employee saat karyawan baru login untuk menghindari overhead scan semua karyawan.',
                    ],
                ],
            ],
        ];
    }

    private function getPimpinanReport(): array
    {
        return [
            [
                'date'    => '14 Agustus 2026',
                'title'   => 'Fix Error 500 Appraisal & Notifikasi, Export Total Gaji Kini Tampilkan Rincian & Rumus (v3.3.15)',
                'summary' => 'Dua halaman yang sempat error 500 (Penilaian Appraisal dan Settings → Notifikasi) sudah ditemukan akar masalahnya dan diperbaiki — keduanya bug penulisan kode tampilan (Blade) yang jarang terjadi, sudah dirapikan supaya tidak terulang di file lain. Sekalian diperbaiki juga proses deploy-nya supaya tidak ada resiko error sesaat setelah update ke depannya. Terkait laporan pimpinan soal nominal Export Total Gaji per Brand yang berbeda dari perhitungan yang sudah dikoreksi: fitur export-nya sekarang dilengkapi rincian penuh — daftar tiap karyawan yang dijumlahkan, kolom sumbernya, dan rumus perhitungan ditulis jelas di sheet terpisah. Ditemukan indikasi kuat bahwa akar selisihnya adalah sumber data: tombol ini masih membaca dari file upload tahunan terpisah ("Summary Tokio-O!") yang tidak tersambung ke data karyawan OMEO, berbeda dari perhitungan payroll/BPJS di menu lain yang sudah pakai data yang terkoreksi. Silakan cek sheet "Formula & Sumber Data" di file export untuk detail lengkapnya, lalu kita diskusikan sumber mana yang seharusnya jadi acuan.',
                'access'  => 'Finance → Summary Gaji Tahunan → Export Excel → Export Total Gaji',
                'howto'   => [
                    'Buka Finance → Summary Gaji Tahunan, klik "Export Excel" → pilih periode bulan → klik "Export Total Gaji"',
                    'File yang terunduh sekarang punya 3 sheet: "Total per Outlet" (angka ringkasan), "Detail per Karyawan" (rincian tiap baris), dan "Formula & Sumber Data" (penjelasan rumus & sumber data)',
                    'Cek sheet terakhir untuk lihat kenapa angkanya bisa berbeda dari perhitungan yang sudah dikoreksi pimpinan',
                ],
                'stats'   => '✅ 2 bug error 500 diperbaiki (akar masalah) | Fitur baru: rincian & rumus di Export Total Gaji | File diubah/baru: 3',
            ],
            [
                'date'    => '12 Agustus 2026',
                'title'   => 'Appraisal: Fix Data Tercampur, Error Perpanjang Due Date, Reminder & Template Email (v3.3.14)',
                'summary' => 'Tindak lanjut feedback appraisal putaran kedua. Kasus "Henry" (data terlihat dobel, 22 evaluator padahal cuma 5-6 yang diundang) sudah ditelusuri sampai akarnya: halaman Monitoring, Laporan, dan Detail Karyawan ternyata tidak pernah membatasi tampilan ke satu periode — appraisal periode berjalan otomatis tergabung dengan seluruh riwayat lama (termasuk data migrasi dari sistem MEO lama) jadi satu angka. Sekarang ketiga halaman itu otomatis fokus ke periode yang sedang aktif, riwayat lama tetap bisa dilihat lewat pilihan "Semua Periode" kalau memang dibutuhkan. Error 500 saat perpanjang due date juga sudah ditemukan akarnya (tabrakan data kalau tombol diklik dua kali cepat) dan diperbaiki, sekaligus menambahkan jeda 24 jam untuk tombol reminder supaya tidak bisa ter-spam tidak sengaja. Terakhir, halaman Settings → Notifikasi yang selama ini terlihat bisa mengatur pesan email ternyata tidak pernah benar-benar berpengaruh — sekarang sudah tersambung dengan benar, lengkap dengan fitur baru lampiran file per jenis notifikasi.',
                'access'  => 'Appraisal HRD → Monitoring / Laporan Appraisal (filter Periode) | Settings → Notifikasi (template pesan & lampiran email) | Settings → Panduan Penggunaan (tutorial cara pakai)',
                'howto'   => [
                    'Monitoring/Laporan: pilih periode di dropdown "Periode" kalau ingin lihat data periode tertentu atau riwayat lama — default sudah otomatis periode aktif',
                    'Reminder evaluator: tombol otomatis nonaktif dengan keterangan jam kalau baru dikirim dalam 24 jam terakhir, tidak perlu dikira-kira manual',
                    'Atur pesan email: buka Settings → Notifikasi → bagian "Template Pesan Ringkas", ubah judul/isi pesan per jenis notifikasi appraisal — perubahan langsung berlaku ke email berikutnya',
                    'Tambah lampiran email: di bagian template yang sama, upload file (PDF/gambar/dokumen) di kolom "Lampiran Email" — otomatis terlampir di setiap email jenis itu ke depannya',
                    'Kalau butuh panduan cara pakai fitur-fitur di atas, buka menu Settings → Panduan Penggunaan (halaman baru, isinya tutorial langkah demi langkah)',
                ],
                'stats'   => '✅ Bug data tercampur antar periode, error 500 due date, & template email mati diperbaiki (akar masalah) | Fitur baru: jeda reminder 24 jam, lampiran email, halaman Panduan Penggunaan | File diubah/baru: 10',
            ],
            [
                'date'    => '5 Agustus 2026',
                'title'   => 'Appraisal: Skor Tunggal, TTD Dinamis, Notifikasi Email, Shift Outlet (v3.3.13)',
                'summary' => 'Tindak lanjut dari review pimpinan Sabtu lalu atas modul Appraisal. Kriteria penilaian yang terlihat dobel di form evaluator ternyata bug nyata (bukan sekadar tampilan) — sudah diperbaiki dari akarnya, dan halaman Kelola Kriteria dirombak jadi tab Office/Operational sesuai arahan. Saat verifikasi di server production, ditemukan lagi akar masalah yang lebih dalam: template "KRITERIA PENILAIAN OFFICE" dan "KRITERIA OPERASIONAL OUTLET" ternyata belum pernah dikaitkan ke kategori karyawan sejak dibuat, sehingga SEMUA appraisal (lama & baru) selama ini otomatis memakai template Default — sudah diperbaiki juga, appraisal baru untuk Office/Operational sekarang otomatis memakai kriteria yang benar sesuai kategori karyawannya. Kebingungan angka rata-rata (79.2 vs 4.18) juga sudah ditelusuri: dua sistem skor berbeda dihitung terpisah di beberapa tempat kode dengan label yang tidak konsisten — sekarang disatukan jadi satu angka (skala 1-5) di semua halaman, sesuai arahan pimpinan. Fitur Tanda Tangan Digital dirombak total dari 5 slot tetap jadi 3 slot default (Karyawan otomatis, 2 kategori bisa diganti HRD) dengan tombol tambah sampai maksimal 4, plus kategori baru "Owner In Charge" untuk pemilik outlet cabang/franchise. Notifikasi appraisal sekarang juga masuk email, tidak cuma inbox internal. Terakhir, outlet operational sekarang bisa punya beberapa shift kerja dengan presensi yang otomatis mencocokkan ke shift terdekat.',
                'access'  => 'Appraisal HRD → Laporan Appraisal → Detail Karyawan (skor, TTD) | Appraisal HRD → Kriteria Penilaian (tab Office/Operational) | Master Outlet → Master Shift Kerja | Master Outlet → edit outlet (Owner In Charge)',
                'howto'   => [
                    'Skor appraisal: buka Laporan Appraisal, angka yang ditampilkan sekarang konsisten skala 1-5 di semua halaman dan file export',
                    'Tanda Tangan Digital: buka Detail Karyawan appraisal, pilih kategori tiap slot TTD (PIC/HRD/Manager/dst), klik "+ Tambah TTD" kalau butuh lebih dari 3',
                    'Owner In Charge: isi dulu namanya di Master Outlet → edit outlet, baru bisa dipilih sebagai kategori TTD',
                    'Master Shift Kerja: buka menu Master Shift Kerja, tambahkan shift per outlet operational (jam masuk/pulang) — presensi otomatis menyesuaikan',
                ],
                'stats'   => '✅ Bug kriteria duplikat, salah pilih template Office/Operational, & skor ganda diperbaiki (akar masalah) | Fitur baru: TTD Dinamis, Owner In Charge, Notifikasi Email, Master Shift | File diubah/baru: 33+',
            ],
            [
                'date'    => '3 Agustus 2026',
                'title'   => 'Cross-Billing BPJS: Sinkronisasi Otomatis Karyawan-PT (v3.3.12)',
                'summary' => 'Penyempurnaan dari fitur Cross-Billing kemarin. Sebelumnya, setiap kali ada tagihan BPJS baru yang selesai direview, data relasi "karyawan ini bayar iuran lewat PT mana" harus di-update manual lewat command di server — kalau lupa dijalankan, tab Cross-Billing bisa terlihat kosong padahal tagihannya sudah lengkap direview. Sekarang prosesnya otomatis: begitu HRD klik "Konfirmasi Review", jalankan ulang matching, atau konfirmasi kecocokan karyawan secara manual, sistem langsung mencatat relasinya sendiri — tidak ada langkah tambahan yang perlu diingat. Sifatnya juga dijaga aman: proses ini hanya menambah data baru, tidak pernah mengubah atau menimpa data yang sudah benar sebelumnya, jadi kalaupun dijalankan berkali-kali hasilnya tetap konsisten.',
                'access'  => 'Finance → Rekonsiliasi BPJS → (otomatis berjalan di balik layar saat Review dikonfirmasi)',
                'howto'   => [
                    'Tidak ada langkah tambahan — cukup lanjutkan alur seperti biasa: upload tagihan → review nama/NIK → klik "Konfirmasi Review"',
                    'Setelah konfirmasi, pesan di layar akan menyebutkan berapa relasi karyawan-PT baru yang tercatat (kalau ada)',
                    'Cek hasilnya di Finance → Cross-Billing BPJS → tab Per PT / Per Outlet, data akan langsung muncul tanpa perlu akses server',
                ],
                'stats'   => '✅ Otomatisasi sinkronisasi data Cross-Billing | Tidak ada lagi ketergantungan command manual di server | File diubah/baru: 3',
            ],
            [
                'date'    => '3 Agustus 2026',
                'title'   => 'BPJS: Nama dari Data Karyawan, Email Login, Cross-Billing per PT (v3.3.11)',
                'summary' => 'Perbaikan besar untuk masalah nama karyawan yang sering salah/geser saat upload tagihan BPJS PDF. Akar masalahnya sudah ditemukan: sistem sebelumnya membaca nama dari teks PDF, yang gampang salah kalau nama karyawan panjang dan terpaksa ditulis 2 baris di dokumen aslinya. Sekarang nama diambil langsung dari data karyawan OMEO berdasarkan NIK (yang selalu terbaca akurat dari PDF) — jauh lebih bisa diandalkan. Kalau NIK belum terdaftar, sistem kasih tahu jelas "belum ada di sistem" alih-alih menampilkan nama yang mungkin salah. HRD juga dikasih alat koreksi manual: edit NIK langsung, tukar NIK dengan baris tetangga, atau gabung nama yang nyasar — semuanya aman, tidak ada data yang terhapus. Selain itu, HRD sekarang bisa ganti email login karyawan langsung dari halaman Users & Roles (sebelumnya harus lewat database), dan laporan Cross-Billing BPJS per PT sekarang menunjukkan jelas PT/outlet mana yang harus ditagih kalau ada selisih penanggung BPJS.',
                'access'  => 'Finance → Rekonsiliasi BPJS → Review Nama Karyawan | HRD → Users & Roles | Finance → Cross-Billing BPJS → tab Per PT',
                'howto'   => [
                    'Review BPJS: upload tagihan seperti biasa, nama karyawan otomatis muncul dari data OMEO kalau NIK cocok (tanda ✅ hijau). Kalau muncul tanda ⚠️ kuning "Belum ada di sistem", cek NIK-nya — kalau salah baca, klik NIK untuk edit, nama akan otomatis ketemu lagi',
                    'Kalau posisi NIK & baris tertukar dengan baris sebelah, pakai tombol ▲▼ di sebelah NIK untuk menukar',
                    'Ubah email login: buka HRD → Users & Roles, cari nama user, klik "Ubah email login" di kolom email',
                    'Cross-Billing per PT: buka Finance → Cross-Billing BPJS, lihat kolom "Ditagih ke" di sebelah kanan tiap karyawan',
                ],
                'stats'   => '✅ Bug kritikal nama/NIK BPJS diperbaiki (akar masalah, bukan tambal sulam) | Fitur baru: Edit Email Login, Cross-Billing "Ditagih ke" | File diubah/baru: 12',
            ],
            [
                'date'    => '30 Juli 2026',
                'title'   => 'Appraisal: Monitoring per Karyawan, Koreksi Nilai, Print Out PDF (v3.3.10)',
                'summary' => 'Lanjutan masukan HRD atas modul appraisal. Halaman Monitoring sekarang dikelompokkan per karyawan (bukan per evaluator lagi) sehingga HRD lebih cepat lihat progress — misalnya "3/5 evaluator submit" dalam satu baris, lengkap dengan filter departemen, status, dan due date terlewat. Tombol "Print Out" yang sebelumnya mencetak halaman web mentah sekarang membuka file PDF rapi. Yang paling penting: HRD sekarang punya dua cara menangani evaluator yang salah kasih nilai — bisa langsung "exclude" dari perhitungan tanpa hapus data, atau evaluator sendiri bisa minta izin edit ulang (maksimal 2x, harus disetujui HRD, dengan reminder ke kedua pihak). Data appraisal lama juga sudah dikonversi otomatis ke label klasifikasi baru.',
                'access'  => 'Appraisal HRD → Monitoring Appraisal (grouping baru) | Laporan Appraisal → Detail Karyawan → tombol Exclude/Perpanjang Due Date/Approve Edit Request',
                'howto'   => [
                    'Monitoring: gunakan filter departemen/status/due date terlewat untuk cari karyawan yang perlu ditindaklanjuti, klik "Detail" untuk lihat per evaluator',
                    'Exclude nilai salah: buka Laporan Appraisal → Detail Karyawan, klik "Exclude" di bawah nama evaluator yang nilainya salah — nilai itu langsung tidak ikut dihitung rata-rata',
                    'Approve edit ulang: kalau evaluator sudah mengajukan izin edit, akan muncul panel kuning di atas halaman Detail Karyawan — klik Setujui/Tolak',
                    'Perpanjang due date massal: buka Detail Karyawan, klik "Perpanjang Due Date — Semua Evaluator"',
                ],
                'stats'   => '✅ Monitoring di-redesign (grouping per karyawan) | Fitur baru: Exclude Nilai, Request Edit (maks 2x), Perpanjang Due Date Massal | Bug diperbaiki: Print Out | File diubah/baru: 10',
            ],
            [
                'date'    => '30 Juli 2026',
                'title'   => 'Appraisal: Perpanjang Due Date, Skor Gaya IPK, Template Kriteria per Kategori (v3.3.9)',
                'summary' => 'Empat perbaikan sekaligus atas masukan HRD dan owner soal proses appraisal. Pertama, due date appraisal sekarang bisa diperpanjang langsung oleh HRD/Admin (dengan alasan wajib) tanpa perlu ubah data manual. Kedua, hasil penilaian yang dulu labelnya "Bagus/Cukup/dst" diganti jadi klasifikasi gaya IPK (Outstanding, Exceed Expectation, dst — 6 tingkat) sesuai arahan owner. Ketiga, ada halaman "Panduan Skor Penilaian" baru yang menjelaskan prinsip penilaian dan tabel klasifikasi, ditampilkan juga sebagai pengingat di form penilaian supaya evaluator menilai berdasarkan acuan yang sama, bukan kesan pribadi. Keempat — yang paling besar — sekarang HRD bisa membuat set kriteria penilaian yang berbeda untuk karyawan Office vs Operational Outlet (atau kategori lain), dan sistem otomatis memilih kriteria yang sesuai saat appraisal dibuat.',
                'access'  => 'Appraisal HRD → Kriteria Penilaian → Kelola Template | Menu Appraisal → Panduan Skor Penilaian | Detail Appraisal → kartu Due Date',
                'howto'   => [
                    'Perpanjang due date: buka detail appraisal, klik "Perpanjang due date" di kartu Due Date, isi tanggal baru + alasan',
                    'Panduan skor: buka menu Appraisal → Panduan Skor Penilaian, atau klik banner pengingat di atas form penilaian evaluator',
                    'Template kriteria: buka Appraisal HRD → Kriteria Penilaian → "Kelola Template", buat template baru atau klik "Duplikat" dari template Default lalu sesuaikan kriterianya, pilih kategori karyawan (Office/Outlet/Production) supaya otomatis terpakai',
                ],
                'stats'   => '✅ Fitur baru: Perpanjang Due Date, Panduan Skor Penilaian, Template Kriteria per Kategori | Klasifikasi skor diganti ke 6-tingkat gaya IPK | File diubah/baru: 20',
            ],
            [
                'date'    => '27 Juli 2026',
                'title'   => 'Slip Gaji Karyawan (v3.3.8)',
                'summary' => 'Fitur baru: Slip Gaji karyawan langsung dari data payroll yang sudah diimport ke sistem — tidak perlu lagi buat manual. HRD/Finance tinggal pilih periode dan karyawan, lalu bisa lihat dulu (preview) sebelum diunduh. Slip berisi rincian pendapatan (gaji pokok, tunjangan, uang hadir, HR, lembur, S.Expense), potongan (BPJS Ketenagakerjaan, BPJS Kesehatan, potongan lain), sampai Take Home Pay, lengkap dengan nomor rekening bank karyawan kalau sudah terdaftar. Ini masih versi dasar — komponen tambahan seperti PPh21 dan rincian jenis potongan akan menyusul setelah kebutuhannya dipastikan.',
                'access'  => 'Finance → Slip Gaji → pilih periode & karyawan → Preview / Unduh',
                'howto'   => [
                    'Buka Finance → Slip Gaji',
                    'Pilih Periode (bulan payroll), Outlet (opsional), atau cari nama karyawan',
                    'Klik "Preview" untuk lihat slip di tab baru tanpa langsung terunduh, atau "Unduh" untuk simpan file PDF-nya',
                ],
                'stats'   => '✅ Fitur baru: Slip Gaji | Sumber data: payroll yang sudah diimport | File diubah/baru: 5',
            ],
            [
                'date'    => '27 Juli 2026',
                'title'   => 'BPJS Parser Fix & Export PDF Bulk Appraisal (v3.3.7)',
                'summary' => 'Bug lama di parser tagihan BPJS PDF akhirnya ditemukan akar masalahnya: filter otomatis yang seharusnya membuang baris "grand total" ternyata salah membuang kolom Upah, JHT Pemberi Kerja, dan Total Iuran yang sah — mengakibatkan SEMUA karyawan di tagihan tersebut (bukan cuma yang di halaman terakhir) punya nilai iuran yang salah/geser. Sudah diperbaiki dan diverifikasi langsung dengan tagihan PT Imperial Prima Food (34 karyawan, 2 halaman) — semua nilai sekarang cocok persis dengan dokumen aslinya. Selain itu, halaman Laporan Appraisal sekarang punya tombol "Export PDF Semua" untuk mengunduh laporan detail banyak karyawan sekaligus dalam 1 file, tidak perlu lagi export satu-satu.',
                'access'  => 'Finance → Rekonsiliasi BPJS → Upload Tagihan | Appraisal HRD → Laporan Appraisal → tombol "Export PDF Semua"',
                'howto'   => [
                    'BPJS: upload ulang tagihan multi-halaman yang sebelumnya hasilnya meragukan — sekarang seharusnya sudah akurat',
                    'Appraisal: buka Laporan Appraisal, atur filter periode/status/pencarian sesuai kebutuhan, lalu klik "Export PDF Semua" — 1 file PDF berisi semua karyawan yang cocok filter, satu bagian per karyawan',
                ],
                'stats'   => '✅ Bug kritikal BPJS parser diperbaiki (mempengaruhi semua tagihan multi-halaman) | Fitur baru: Export PDF Bulk Appraisal | File diubah/baru: 7',
            ],
            [
                'date'    => '27 Juli 2026',
                'title'   => 'Sprint I & K: BPJS Cross-Billing dan Penugasan Outlet (v3.3.6)',
                'summary' => 'Dua pekerjaan besar selesai sekaligus. Pertama, sistem Cross-Billing BPJS kini benar-benar berfungsi: PT/badan hukum otomatis terdeteksi dari file tagihan BPJS yang diupload (tidak perlu isi master manual), dan laporan baru per-outlet menunjukkan outlet mana membayar BPJS untuk karyawan outlet lain serta outlet mana yang harus ditagih. Kedua, riwayat penugasan outlet karyawan (termasuk karyawan yang kerja di lebih dari satu outlet dalam sebulan) kini otomatis tercatat dari data payroll. Selain itu, Master Departemen dirapikan (4 duplikat digabung), Master Outlet dilengkapi field PT, PDF export presensi diperbaiki (judul salah + sekarang 1 halaman per karyawan), dan halaman Struktur Organisasi yang sempat error total sudah diperbaiki.',
                'access'  => 'Finance → Laporan Cross-Billing BPJS (tab Per PT / Per Outlet) | Detail Karyawan → tab Penugasan | Master Departemen | Master Outlet | HRD → Rekap Presensi → Export PDF | Master Posisi → Struktur Organisasi',
                'howto'   => [
                    'Cross-Billing BPJS: buka Finance → Laporan Cross-Billing BPJS, pilih tab "Per PT" untuk lihat total per PT, atau tab "Per Outlet" untuk lihat siapa membayar untuk siapa',
                    'Master Outlet: isi field "PT / Badan Hukum" untuk tiap outlet supaya laporan Cross-Billing per Outlet semakin akurat',
                    'Penugasan Karyawan: buka Detail Karyawan, scroll ke bagian "Penugasan" untuk lihat riwayat outlet & departemen (terisi otomatis, bisa ditambah manual)',
                    'Rekap Presensi: klik "Export PDF" seperti biasa — sekarang tiap karyawan dapat halaman sendiri',
                ],
                'stats'   => '✅ Departemen dirapikan: 4 digabung, 6 ditata ulang | PT BPJS ter-auto-detect | Halaman baru: Cross-Billing per Outlet, Penugasan Karyawan | Bug diperbaiki: 5 | File diubah/baru: 27',
            ],
            [
                'date'    => '22 Juli 2026',
                'title'   => 'Annual Summary Export Fix (v3.3.5)',
                'summary' => 'Fitur Export Detail di halaman Summary Gaji Tahunan telah diperbaiki secara menyeluruh. Filter outlet kini bekerja dengan benar — ketika filter Gressmall dipilih, hanya data Gressmall yang ter-export dengan total yang akurat sesuai data payroll asli. Kolom NIK kini muncul dengan 16 digit penuh, No.Komp tampil dengan leading zero, dan 27 outlet MKO serta QUALI yang sebelumnya tidak ter-filter kini sudah ter-mapping dengan benar.',
                'access'  => 'Finance → Summary Gaji Tahunan → pilih tahun & outlet → klik "Export Detail"',
                'howto'   => [
                    'Buka halaman Summary Gaji Tahunan',
                    'Pilih Tahun (default: tahun berjalan)',
                    'Pilih Outlet yang ingin di-export (opsional)',
                    'Klik tombol "Export Detail"',
                    'File Excel berisi sheet per bulan + sheet SUMMARY DETAIL',
                    'Sheet SUMMARY DETAIL: kolom No, No.Komp, NIK, Nama, Posisi, Outlet, lalu sub-kolom per bulan (Gaji Pokok, HR, Uang Hadir, Tunjangan LK, Tunjangan RnD, Rapelan, BPJS TK, BPJS Kes, Total), dan kolom Total Tahunan',
                ],
                'stats'   => '✅ Bug diperbaiki: 8 | Outlet ter-mapping: 27 (MKO + QUALI) | Records ter-update outlet_id: 4.695 | File diubah: 1 (AnnualSummaryController.php)',
            ],
            [
                'date'    => '21 Juli 2026',
                'title'   => 'Pengaturan Bobot Formula Appraisal (v3.3.4)',
                'summary' => 'HRD kini dapat mengatur sendiri persentase kontribusi setiap komponen penilaian (Kriteria Bintang, KPI, Training, Skill, Posisi) langsung dari halaman setting — tanpa perlu hubungi programmer. Tersedia 2 level setting: Global sebagai default, dan Per-Tipe untuk Probation, Annual, dan Contract Renewal. Formula scoring otomatis menyesuaikan jika salah satu komponen tidak aktif pada appraisal tertentu.',
                'access'  => 'Appraisal HRD → Bobot Formula Appraisal (atau: /appraisals/weight-config)',
                'howto'   => [
                    'Buka menu "Bobot Formula Appraisal" di sidebar Appraisal HRD',
                    'Tab "Setting Global" berlaku untuk semua tipe appraisal jika tidak ada setting khusus',
                    'Klik tab "Probation", "Annual Review", atau "Contract Renewal" untuk setting per-tipe',
                    'Ubah angka bobot tiap komponen — rumus aktif terupdate otomatis di bawah',
                    'Klik "Simpan Setting" saat total bobot sudah tepat 100%',
                    'Untuk reset ke global: klik "Hapus / Gunakan Global" di tab per-tipe',
                ],
                'stats'   => '✅ Halaman baru: 1 | Komponen yang dapat diatur: 5 | Level setting: 2 (Global + Per-Tipe) | File diubah: 4 (Controller, Service, Routes, Menu)',
            ],
            [
                'date'    => '21 Juli 2026',
                'title'   => 'Migrasi Data Historis Appraisal MEO (v3.3.3)',
                'summary' => 'Seluruh data appraisal dari aplikasi MEO lama telah berhasil dipindahkan ke OMEO secara otomatis. 136 penilaian dari 19 karyawan kini tersedia di halaman Laporan Appraisal dengan badge "Historis MEO" sebagai pembeda. Data karyawan resign secara otomatis di-skip. Skor dikonversi proporsional dari skala lama (1-4) ke skala baru (skala 100).',
                'access'  => 'Appraisal HRD → Laporan Appraisal → badge 📂 Historis MEO di nama karyawan yang datanya dari MEO lama',
                'howto'   => [
                    'Buka Laporan Appraisal — data historis MEO sudah tampil',
                    'Badge "📂 Historis MEO" menandai data yang dimigrasi',
                    'Untuk jalankan ulang migrasi (jika ada data baru di MEO): php artisan appraisal:migrate-from-meo --dry-run (preview)',
                    'Jika preview aman: php artisan appraisal:migrate-from-meo (eksekusi)',
                ],
                'stats'   => '✅ Appraisal dimigrasi: 136 | Karyawan tercakup: 19 | Karyawan di-skip (resign): 2 (Robby, Raymond) | Periode data: Agustus 2025 – Juli 2026 | File baru: 2 (Command + Migration)',
            ],
            [
                'date'    => '20 Juli 2026',
                'title'   => 'Appraisal Report & Privacy (v3.3.2)',
                'summary' => 'Sistem appraisal kini memiliki halaman laporan terpusat yang menampilkan semua karyawan dalam satu tampilan, dikelompokkan per individu dengan detail per evaluator. Privacy evaluator terjaga — karyawan yang dinilai hanya melihat alias, bukan nama asli penilai. Bug perhitungan skor KPI juga telah diperbaiki agar tidak merugikan karyawan.',
                'access'  => 'Appraisal HRD → Laporan Appraisal (atau: /appraisals/report)',
                'howto'   => [
                    'Buka menu "Laporan Appraisal" di sidebar Appraisal HRD',
                    'Gunakan filter Periode dan Status untuk menyaring data',
                    'Klik baris karyawan untuk expand detail per evaluator',
                    'Gunakan search untuk cari nama karyawan spesifik',
                ],
                'stats'   => '✅ Halaman baru: 1 (Laporan Appraisal) | Bug diperbaiki: 2 (KPI scoring + privacy leak) | File diubah: 5',
            ],
            [
                'date'    => '14 Juli 2026',
                'title'   => 'BPJS Cross-billing & Parser Upgrade (v3.3.1)',
                'summary' => 'Sistem BPJS kini jauh lebih andal. Parser PDF dan XLSX diperbaiki secara mendasar sehingga nama dan total iuran terbaca akurat. Fitur baru Cross-billing memungkinkan Finance melihat dengan tepat karyawan dari PT mana yang iurannya dibayar oleh PT lain, berapa jumlahnya, dan outlet mana yang harus membayar tagihan balik — lengkap dengan export Excel.',
                'access'  => 'Finance → Rekonsiliasi BPJS → [pilih tagihan] → klik "📊 Cross-billing"',
                'howto'   => [
                    'Buka halaman detail tagihan BPJS',
                    'Klik tombol "📊 Cross-billing" di header halaman',
                    'Pilih referensi payroll (periode) di dropdown',
                    'Klik accordion outlet untuk melihat daftar karyawan',
                    'Klik summary card untuk popup daftar nama per kategori',
                    'Klik "⬇ Export Excel" untuk rekap per outlet',
                ],
                'stats'   => '✅ Bug parser diperbaiki: 4 (fragment nama, grand total, multi-page, float NIK) | Format baru didukung: 1 (XLSX Kopijaya 28-kolom) | Fitur baru: 3 (Review Nama, Re-parse, Cross-billing) | File diubah: 5',
            ],
            [
                'date'    => '13 Juli 2026',
                'title'   => 'Positions & Org Chart Visual (v3.3.0)',
                'summary' => 'Sistem kini memiliki struktur organisasi digital yang lengkap. HRD dapat melihat seluruh posisi per departemen, mengetahui berapa karyawan di setiap posisi, dan melihat siapa saja yang menempati posisi tersebut secara visual — lengkap dengan foto profil, status kontrak, dan outlet tempat bertugas.',
                'access'  => 'Master Perusahaan → Posisi & Departemen → Lihat Org Chart (atau langsung: /positions/org-chart)',
                'howto'   => [
                    'Buka halaman Posisi & Departemen untuk CRUD dan import/export',
                    'Klik "🌳 Lihat Org Chart" untuk tampilan visual',
                    'Klik card posisi manapun → panel kanan muncul',
                    'Panel berisi foto + nama + outlet setiap karyawan di posisi itu',
                    'Gunakan search di panel untuk cari karyawan spesifik',
                ],
                'stats'   => '✅ Posisi ter-seed: 13 | Departemen ter-seed: 10 | Karyawan ter-migrasi: 1.834 | File diubah: 8',
            ],
            [
                'date'    => '13 Juli 2026',
                'title'   => 'Notifikasi Smart Filter — Privasi & Relevansi (v3.2.2)',
                'summary' => 'Sistem notifikasi OMEO kini berfungsi seperti media sosial perusahaan — setiap karyawan hanya melihat notifikasi yang relevan untuk mereka. Informasi internal HRD (probation reminder, perubahan profil, appraisal) tidak lagi bocor ke inbox karyawan biasa. HRD dan Finance tetap menerima semua notifikasi operasional.',
                'access'  => 'Bell icon (🔔) di navbar → klik untuk preview → "Lihat Semua" → halaman inbox lengkap dengan filter tab',
                'howto'   => [
                    'Klik bell icon di navbar untuk melihat preview notifikasi',
                    'Buka halaman notifikasi untuk filter per tipe atau tanggal',
                    'Klik tab tipe (Appraisal, Kontrak, dll) untuk filter',
                    'Notifikasi karyawan: hanya yang ditujukan ke mereka',
                    'Notifikasi HRD/Finance/Admin: semua notifikasi operasional',
                ],
                'stats'   => '✅ Bug diperbaiki: 1 (probation_reminder broadcast ke semua) | Notifikasi dimigrasi: 3 (NULL → spesifik ke 3 HRD user) | File diubah: 4 (Service + Controller + 2 Views)',
            ],
            [
                'date'    => '12 Juli 2026',
                'title'   => 'Walk-in: Antrian Otomatis per Posisi (v3.2.1)',
                'summary' => 'Dashboard walk-in kini memiliki tab antrian otomatis per posisi yang dilamar kandidat. Tim rekrutmen dapat memantau antrian COOK, BAR, SERVICE, KASIR (dan posisi lainnya) secara terpisah, dengan nomor antrian yang urut otomatis berdasarkan waktu check-in.',
                'access'  => 'Rekrutmen → Walk-in → [pilih event] → Dashboard → Section "Antrian per Posisi" di atas tabel kandidat',
                'howto'   => [
                    'Buka dashboard event walk-in yang sedang berjalan',
                    'Lihat section "Antrian per Posisi" di bagian atas',
                    'Klik tab posisi (COOK/BAR/SERVICE/KASIR/dll) untuk melihat antrian per posisi',
                    'Nomor antrian otomatis terurut sesuai waktu check-in',
                    'Kandidat yang check-in duluan mendapat nomor lebih kecil',
                ],
                'stats'   => '✅ Fitur baru: 1 (Tab antrian per posisi) | Tabel diubah: 0 | File diubah: 2 (Controller + View)',
            ],
            [
                'date'    => '11 Juli 2026',
                'title'   => 'Sprint I — BPJS Cross-billing & Finance Enhancements (v3.2.0)',
                'summary' => 'Update ini membawa fitur baru di area BPJS dan Finance, serta perbaikan di beberapa modul HRD. Fitur unggulan: HRD kini bisa mencatat karyawan yang BPJS-nya ditanggung PT berbeda (karyawan rolling), lengkap dengan laporan nominal iuran per bulan. Finance mendapat template transfer Bank Mandiri format MCM 2.0 dan rekap total gaji per outlet. Di sisi perbaikan: profil karyawan lebih lengkap, NIK sinkron otomatis, filter presensi fleksibel, dan form pendaftaran kandidat tidak lagi bermasalah saat upload dokumen.',
                'access'  => 'Master BPJS → BPJS Assignment & Cross-billing BPJS | Finance → Summary Gaji Tahunan | Employees → profil karyawan',
                'howto'   => [
                    '[BPJS Assignment] Menu Master BPJS → BPJS Assignment → klik "+ Tambah Assignment" atau upload Excel bulk',
                    '[Cross-billing] Menu Master BPJS → Cross-billing BPJS → pilih periode → lihat karyawan rolling per PT beserta nominal iuran',
                    '[Export Excel Cross-billing] Di halaman Cross-billing → klik "Export Excel" → tiap PT dapat sheet tersendiri',
                    '[Template Mandiri] Finance → Summary Gaji Tahunan → dropdown "Template Mandiri" → pilih periode & isi keterangan → download XLSX atau CSV',
                    '[Total Gaji per Outlet] Finance → Summary Gaji Tahunan → dropdown "Export Excel" → pilih bulan → "Export Total Gaji"',
                    '[Rekening Bank] Employees → klik nama karyawan → Tab Payroll → kelola rekening bank (bisa lebih dari satu)',
                ],
                'stats'   => '✅ Sudah live — siap dipakai HRD & Finance',
            ],
            [
                'date'    => '30 Juni 2026',
                'title'   => 'Sistem Assignment Appraisal Selesai Disempurnakan',
                'summary' => 'Halaman penugasan penilaian karyawan (Assignment Appraisal) kini menampilkan kandidat probation dalam 3 kelompok visual berdasarkan tingkat urgensi, sehingga HRD bisa memprioritaskan siapa yang harus segera dinilai. HRD juga bisa menentukan kombinasi evaluator yang berbeda untuk setiap karyawan dalam satu kali proses, jauh lebih efisien dibanding sebelumnya.',
                'access'  => 'Menu Appraisal HRD → Assignment Probation',
                'howto'   => [
                    'Pilih tab Probation (Window) atau Manual (Cari Karyawan)',
                    'Lihat 3 kolom: Masih Aman / Segera / Sudah Lewat',
                    'Klik kandidat dari kolom manapun, lalu cari evaluator',
                    'Klik "+ Tambahkan ke Daftar Batch" untuk tiap karyawan',
                    'Ulangi untuk karyawan lain dengan evaluator berbeda',
                    'Setelah semua siap, klik "Generate Semua Draft Appraisal"',
                ],
                'stats'   => '✅ Sudah live & siap dipakai HRD',
            ],
            [
                'date'    => '30 Juni 2026',
                'title'   => 'Walk-In Interview — Proses Seleksi Lengkap',
                'summary' => 'Setelah kandidat mendaftar dan check-in, HRD kini bisa mencatat hasil interview, input skor tes, dan menentukan penempatan outlet langsung dari sistem, tanpa perlu pencatatan manual terpisah.',
                'access'  => 'Menu Recruitment → Walk-In Interview → klik nama kandidat',
                'howto'   => [
                    'Buka event Walk-In yang sedang berjalan',
                    'Klik nama kandidat untuk lihat detail',
                    'Update status Interview: Lolos / Tidak Lolos',
                    'Jika lolos, input hasil tes dan skornya',
                    'Tentukan outlet dan posisi penempatan',
                    'Set status akhir: Diterima / Cadangan / Ditolak',
                ],
                'stats'   => '✅ Sudah live & siap dipakai HRD',
            ],
            [
                'date'    => '29 Juni 2026',
                'title'   => 'Sistem Penilaian Karyawan Diluncurkan',
                'summary' => 'Modul appraisal kini memiliki sistem penilaian yang lebih komprehensif: bintang 1-5 untuk 11 kriteria kerja, input KPI persentase, dan pencatatan hasil training. Skor akhir dihitung otomatis dengan formula KPI 30% + Training 20% + Kriteria 50%.',
                'access'  => 'Menu Appraisal → Generate Penilaian → klik nama karyawan → isi form evaluasi',
                'howto'   => [
                    'Buka Appraisal → Generate Penilaian Baru',
                    'Pilih mode: Probation (otomatis), Manual (pilih bebas), atau Semua Karyawan',
                    'Evaluator mengisi bintang untuk 11 kriteria + KPI % + nilai Training',
                    'Sistem hitung skor akhir otomatis: KPI 30% + Training 20% + Kriteria 50%',
                    'HRD approval → hasil visible ke karyawan (jika fitur self-service aktif)',
                ],
                'stats' => '✅ Sudah live — sistem baru per 29 Juni 2026',
            ],
            [
                'date'    => '26 Juni 2026',
                'title'   => 'Fitur Walk-In Interview Diluncurkan',
                'summary' => 'Sistem rekrutmen walk-in kini tersedia secara digital. HRD dan manager dapat membuat event, share link unik, dan kandidat mendaftar langsung dari HP tanpa perlu aplikasi tambahan.',
                'access'  => 'Menu Recruitment → Walk-In Interview',
                'howto'   => [
                    'Buat event walk-in baru (isi nama, tanggal, posisi)',
                    'Klik "Generate Link Saya" untuk dapatkan link unik',
                    'Share link ke kandidat via WA/IG',
                    'Kandidat daftar langsung dari HP (tanpa install apapun)',
                    'HRD pantau pendaftar real-time di dashboard',
                ],
                'stats' => '✅ Sudah live & dapat ditest',
            ],
            [
                'date'    => '26 Juni 2026',
                'title'   => 'Penugasan Karyawan (Sprint K)',
                'summary' => 'Setiap karyawan kini dapat dicatat bekerja di outlet mana, digaji dari cost center mana. Riwayat perpindahan tersimpan otomatis.',
                'access'  => 'Employees → klik nama karyawan → Tab Penugasan',
                'howto'   => [
                    'Buka profil karyawan',
                    'Klik tab Penugasan',
                    'Klik + Set Penugasan Baru',
                    'Pilih outlet tugas dan payroll outlet',
                ],
                'stats' => '✅ Sudah live',
            ],
            [
                'date'    => '25 Juni 2026',
                'title'   => 'Rekonsiliasi BPJS vs Payroll (Sprint J)',
                'summary' => 'Halaman pencocokan antara tagihan resmi BPJS (PDF) dengan data gaji internal. Sistem otomatis menandai mana yang cocok, mana yang ada selisih, dan mana yang perlu dicek.',
                'access'  => 'Finance → Rekon BPJS vs Payroll',
                'howto'   => [
                    'Pilih periode (misal: April 2026)',
                    'Klik Tampilkan',
                    'Lihat status: Cocok / Selisih / Tidak Cocok',
                    'Export Excel untuk laporan ke Owner',
                ],
                'stats' => '✅ Sudah live — sedang ditest pimpinan',
            ],
            [
                'date'    => '25 Juni 2026',
                'title'   => 'PT BPJS per Karyawan (Sprint I)',
                'summary' => 'Setiap karyawan dapat dicatat dikontrak oleh PT BPJS mana. Riwayat perpindahan antar PT BPJS tersimpan untuk keperluan audit.',
                'access'  => 'Employees → klik nama karyawan → Tab BPJS',
                'howto'   => [
                    'Buka profil karyawan',
                    'Klik tab BPJS',
                    'Klik + Set PT BPJS Aktif',
                    'Pilih PT BPJS dan isi tanggal efektif',
                ],
                'stats' => '✅ Sudah live',
            ],
            [
                'date'    => '23 Juni 2026',
                'title'   => 'Detail Gaji Per Bulan & Export',
                'summary' => 'Tampilan detail 9 komponen gaji per karyawan per bulan: Gaji Pokok, Uang Hadir, Tunjangan, Rapelan, BPJS TK, BPJS Kes, dan Total. Bisa diexport ke Excel.',
                'access'  => 'Finance → Summary Gaji Tahunan → Tab Detail Per Bulan',
                'howto'   => [
                    'Menu Finance → Summary Gaji Tahunan',
                    'Klik tab Detail Per Bulan',
                    'Lihat 9 komponen gaji per bulan per karyawan',
                    'Klik Export Excel → Export Detail untuk download',
                ],
                'stats' => '✅ Sudah live — sudah dipakai pimpinan',
            ],
        ];
    }
}
